/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/tools/app_create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an app
         * @description Create an application in a project's environment: an image or a git source (built by a builder), plus its env, domains, volumes, ports, replicas, port, health check, resources and command. Returns the app and its webhook secret (POST <webhook> with it to deploy). Nothing runs until app_deploy (or deploy=true).
         */
        post: operations["app_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/app_delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete an app
         * @description Delete an app: its service leaves the stack (the stack is removed with its last app), its deployments, checkout, webhook secret and deploy key go. Named volumes are kept.
         */
        post: operations["app_delete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/app_deploy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deploy an app
         * @description Deploy an app's current settings: pull (an image source, pinned to its digest) or fetch and build (a git source), then roll its service in its environment's stack; other apps there are untouched. One deploy runs at a time per app; a new one waits behind it and replaces any other waiting one. Returns the deployment record; follow it with app_deployment_log or the events feed.
         */
        post: operations["app_deploy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/app_deploy_key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Make a deploy key
         * @description Generate an ed25519 deploy key for a git app with an SSH URL: the private key is stored as the org secret app.<name>.deploy-key and becomes the app's credential; the public key is returned to add to the repository's deploy keys (read-only).
         */
        post: operations["app_deploy_key"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/app_deployment_log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * A deployment's log
         * @description A deployment's log (git, build and rollout lines) from byte `offset`. Returns the text, the offset to ask from next, and whether the deployment has finished: poll until done. The same lines stream on the events feed as level `log`.
         */
        post: operations["app_deployment_log"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/app_deployments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * List an app's deployments
         * @description An app's deployments, newest first: trigger, status (queued, building, deploying, done, failed, superseded), commit, image and digest, timestamps.
         */
        post: operations["app_deployments"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/app_env_get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get an app's environment
         * @description An app's environment as .env text (KEY=value lines, comments kept). Secret references read KEY=${{secret.NAME}}; their values are never shown.
         */
        post: operations["app_env_get"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/app_env_set": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set an app's environment
         * @description Replace an app's environment with .env text: KEY=value lines (quotes and # comments as in docker compose; comments are kept), KEY=${{secret.NAME}} for an org secret. Takes effect at the next deploy (deploy=true queues one).
         */
        post: operations["app_env_set"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/app_get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get an app
         * @description An app's settings, stack, service name, current deployment and webhook path. Secrets in its env show as {secret: NAME}, never values.
         */
        post: operations["app_get"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/app_list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * List apps
         * @description An org's apps, optionally only one project's (and environment's).
         */
        post: operations["app_list"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/app_rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Roll back an app
         * @description Redeploy a previous successful deployment's image (by digest when known) and settings, without building. The app's saved settings are not changed, so the next deploy applies them again.
         */
        post: operations["app_rollback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/app_update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update an app
         * @description Change an app's settings: the fields given replace the current ones (a JSON merge patch: null clears a setting; objects merge). Name, project and environment are fixed. Takes effect at the next deploy (deploy=true queues one).
         */
        post: operations["app_update"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/app_webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * An app's webhook
         * @description The app's webhook path and secret, to configure in GitHub (application/json, the secret), Gitea/Forgejo (the secret), GitLab (secret token) or any caller (?token=<secret>). rotate=true makes a new secret first.
         */
        post: operations["app_webhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/environment_create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an environment
         * @description Add an environment (staging, preview, ...) to a project. Its apps run as the stack <project>-<name>.
         */
        post: operations["environment_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/environment_delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete an environment
         * @description Remove an environment that has no apps left from a project.
         */
        post: operations["environment_delete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/environment_list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * List environments
         * @description A project's environments.
         */
        post: operations["environment_list"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Events
         * @description What happened, newest last: deploys, rollouts, health changes, restarts, failures. Pass the last `seq` you saw as `since` to get only newer ones; `wait` (seconds, at most 30) holds the call until one arrives.
         */
        post: operations["events"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/ingress_status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingress status
         * @description The HTTP(S) edge: its listeners, CA and Caddy process; every routed domain with its URL, certificate state (issued, pending, failed, unsupported, cloudflare, none) and live upstreams; domain conflicts and refusals; and each Cloudflare-tunnel org's cloudflared and API sync. Shows the caller's orgs only.
         */
        post: operations["ingress_status"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Overview
         * @description Everything a dashboard shows in one call: the host's CPU and memory (with history), every stack in detail (as stack_status), the sandboxes (status, IP, CPU, memory), and the latest event number for the events tool.
         */
        post: operations["overview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/project_create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a project
         * @description Create a project in an org: a group of environments (default: production), each of which runs its apps as one stack named <project>-<env>.
         */
        post: operations["project_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/project_delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete a project
         * @description Delete a project that has no apps left.
         */
        post: operations["project_delete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/project_list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * List projects
         * @description An org's projects, each with its environments and the apps in each.
         */
        post: operations["project_list"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/sandbox_create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a sandbox
         * @description Create (or reconcile) one sandbox: an incus container or VM to run code in isolation. `spec` is one compose service (docs/spec.md) with container_name set, as an object or YAML text. Remote callers' sandboxes are labelled with their identity, and only managed sandboxes are reachable remotely.
         */
        post: operations["sandbox_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/sandbox_exec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run a command in a sandbox
         * @description Run argv in a sandbox (no shell unless you run one: ["sh", "-c", "..."]) and return its exit code and output (each stream capped at 256 KiB, keeping the end). Uses the sandbox's user and working_dir unless given.
         */
        post: operations["sandbox_exec"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/sandbox_list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * List sandboxes
         * @description List instances (for remote callers: only the ones isb serve manages), optionally filtered by labels (`key` or `key=value`).
         */
        post: operations["sandbox_list"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/sandbox_remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Remove a sandbox
         * @description Delete a sandbox (stopping it first). Not for stack replicas: remove or scale the stack.
         */
        post: operations["sandbox_remove"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/secret_create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a secret
         * @description Create a secret in an org's store (fails if one by that name exists). The value is base64; it is encrypted at rest and never listed.
         */
        post: operations["secret_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/secret_delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete a secret
         * @description Delete a secret. Refused while a deployed stack's services use it.
         */
        post: operations["secret_delete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/secret_get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Read a secret
         * @description A secret's value (base64, in `value`) and metadata.
         */
        post: operations["secret_get"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/secret_inspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inspect a secret
         * @description One secret's metadata (never its value).
         */
        post: operations["secret_inspect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/secret_list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * List secrets
         * @description An org's secrets: name, driver, version, timestamps, labels. Never values.
         */
        post: operations["secret_list"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/secret_recipients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Secret recipients
         * @description The age recipients values are encrypted to (public keys only): the daemon's own key first, then the break-glass recipients. `isb secret encrypt` encrypts compose `age:` values to these.
         */
        post: operations["secret_recipients"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/secret_reencrypt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-encrypt secrets
         * @description Re-encrypt every stored value in the org (or every org, with all=true) to the current recipients: the daemon's key and the break-glass recipients. Run after changing the recipients.
         */
        post: operations["secret_reencrypt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/secret_refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh a secret
         * @description Re-read an externally stored secret from its source now, and roll the stacks using it if its version moved (listed in `rolled`). `name` is a store name, or a stack's driver reference. A no-op for the local store.
         */
        post: operations["secret_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/secret_resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve compose secrets
         * @description Local callers only (`isb up`): the values (base64) of a compose file's store-backed secrets (`external`, `age`, `driver`), read from the org's store and decrypted with the daemon's key.
         */
        post: operations["secret_resolve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/secret_set": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set a secret
         * @description Give a secret a new value (base64), bumping its version; creates it in the local store if missing. Stacks using it roll to the new version (listed in `rolled`).
         */
        post: operations["secret_set"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/server_status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Server status
         * @description isb's version, incus' version, and the load balancer's routes with their backends and counters.
         */
        post: operations["server_status"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/stack_config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stack config
         * @description The compose file a stack was deployed with, resolved, and its secrets as references (store name, driver, version; never values).
         */
        post: operations["stack_config"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/stack_deploy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deploy a stack
         * @description Deploy or update a stack from a docker-compose-style file (isb's format: docs/spec.md). Each service runs `deploy.replicas` incus instances, supervised inside their guests so they survive restarts of this server and of the host. Published ports are load-balanced over healthy replicas. A changed service is rolled out per `deploy.update_config` (stop-first by default; `order: start-first` for no downtime). Returns the change per service; pass wait=true to block until the rollout settles.
         */
        post: operations["stack_deploy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/stack_list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * List stacks
         * @description List deployed stacks with each service's replica, health and rollout state.
         */
        post: operations["stack_list"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/stack_logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stack logs
         * @description Recent output of a service's replicas: the journal of its supervised command, or an OCI image's console.
         */
        post: operations["stack_logs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/stack_redeploy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Redeploy a service
         * @description Replace every replica of a service with a fresh instance, rolling, even though its spec did not change: picks up a moved image tag (docker:app:latest) or changed bind-mounted files.
         */
        post: operations["stack_redeploy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/stack_remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Remove a stack
         * @description Delete a stack's instances and published ports. Named volumes are kept unless volumes=true.
         */
        post: operations["stack_remove"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/stack_rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Roll back a stack
         * @description Go back to the stack's previous deployment. A second rollback undoes the first.
         */
        post: operations["stack_rollback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/stack_scale": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scale a service
         * @description Set a service's replica count (0 stops it without removing it).
         */
        post: operations["stack_scale"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/stack_status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stack status
         * @description One stack in detail: per service its revision, state (converged, updating, paused, waiting, failing), message, every replica (status, health, IP, in rotation, restarts, last probe output) and published ports with their live backends.
         */
        post: operations["stack_status"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    app_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Git sources only: {"builder": {"type": "railpack" | "nixpacks" | "dockerfile" (path, target) | "buildpacks" (builder)}, "args": {K: V}, "untrusted": true (build in a VM)}. */
                    build?: Record<string, never>;
                    /** @description argv (a list) or a command line. */
                    command?: unknown;
                    /** @description Queue a deploy right away. */
                    deploy?: boolean;
                    /** @description [{host, path?, port?, https?, redirect?}] for the ingress; port defaults to the app's port. */
                    domains?: Record<string, never>[];
                    /** @description .env text, or a map {KEY: "value" | {"secret": NAME}}. A secret is an org secret, delivered as the variable. */
                    env?: unknown;
                    /** @description Default production. */
                    environment?: string;
                    /** @description A compose healthcheck: {test, interval, timeout, retries, start_period}. */
                    healthcheck?: Record<string, never>;
                    /** @description [a-z0-9-], unique in the org; the service name in its stack. */
                    name: string;
                    /** @description The org to act in (default: default). */
                    org?: string;
                    /** @description The port the app listens on. */
                    port?: number;
                    /** @description Published host ports, compose syntax (127.0.0.1:8080:80), load-balanced over healthy replicas. */
                    ports?: string[];
                    project: string;
                    replicas?: number;
                    /** @description {cpus, memory} per replica. */
                    resources?: Record<string, never>;
                    /** @description Exactly one of {"image": "docker:nginx:1.27"} or {"git": {"url", "ref" (branch, tag or SHA; default main), "subdir", "auth": {"token_secret": NAME, "username"} | {"ssh_key_secret": NAME}, "submodules": false}}. */
                    source: Record<string, never>;
                    /** @description Named volumes, NAME:/path[:ro]. No host paths. */
                    volumes?: string[];
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    app_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @description The org to act in (default: default). */
                    org?: string;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    app_deploy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @description The org to act in (default: default). */
                    org?: string;
                    /** @description How long wait may take, e.g. 10m (default 15m). */
                    timeout?: string;
                    /** @description Wait until the deployment finishes (default false). */
                    wait?: boolean;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    app_deploy_key: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @description The org to act in (default: default). */
                    org?: string;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    app_deployment_log: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    deployment: number;
                    name: string;
                    offset?: number;
                    /** @description The org to act in (default: default). */
                    org?: string;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    app_deployments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    limit?: number;
                    name: string;
                    /** @description The org to act in (default: default). */
                    org?: string;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    app_env_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @description The org to act in (default: default). */
                    org?: string;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    app_env_set: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    deploy?: boolean;
                    /** @description The .env text. */
                    env: string;
                    name: string;
                    /** @description The org to act in (default: default). */
                    org?: string;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    app_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @description The org to act in (default: default). */
                    org?: string;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    app_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    environment?: string;
                    /** @description The org to act in (default: default). */
                    org?: string;
                    project?: string;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    app_rollback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description The deployment to go back to (default: the last successful one before the current). */
                    deployment?: number;
                    name: string;
                    /** @description The org to act in (default: default). */
                    org?: string;
                    /** @description How long wait may take, e.g. 10m (default 15m). */
                    timeout?: string;
                    /** @description Wait until the deployment finishes (default false). */
                    wait?: boolean;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    app_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Git sources only: {"builder": {"type": "railpack" | "nixpacks" | "dockerfile" (path, target) | "buildpacks" (builder)}, "args": {K: V}, "untrusted": true (build in a VM)}. */
                    build?: Record<string, never>;
                    /** @description argv (a list) or a command line. */
                    command?: unknown;
                    /** @description Queue a deploy after the change. */
                    deploy?: boolean;
                    /** @description [{host, path?, port?, https?, redirect?}] for the ingress; port defaults to the app's port. */
                    domains?: Record<string, never>[];
                    /** @description .env text, or a map {KEY: "value" | {"secret": NAME}}. A secret is an org secret, delivered as the variable. */
                    env?: unknown;
                    /** @description A compose healthcheck: {test, interval, timeout, retries, start_period}. */
                    healthcheck?: Record<string, never>;
                    name: string;
                    /** @description The org to act in (default: default). */
                    org?: string;
                    /** @description The port the app listens on. */
                    port?: number;
                    /** @description Published host ports, compose syntax (127.0.0.1:8080:80), load-balanced over healthy replicas. */
                    ports?: string[];
                    replicas?: number;
                    /** @description {cpus, memory} per replica. */
                    resources?: Record<string, never>;
                    /** @description Exactly one of {"image": "docker:nginx:1.27"} or {"git": {"url", "ref" (branch, tag or SHA; default main), "subdir", "auth": {"token_secret": NAME, "username"} | {"ssh_key_secret": NAME}, "submodules": false}}. */
                    source?: Record<string, never>;
                    /** @description Named volumes, NAME:/path[:ro]. No host paths. */
                    volumes?: string[];
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    app_webhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @description The org to act in (default: default). */
                    org?: string;
                    rotate?: boolean;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    environment_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @description The org to act in (default: default). */
                    org?: string;
                    project: string;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    environment_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @description The org to act in (default: default). */
                    org?: string;
                    project: string;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    environment_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description The org to act in (default: default). */
                    org?: string;
                    project: string;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    events: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    limit?: number;
                    /** @description The org to act in (default: default). */
                    org?: string;
                    since?: number;
                    wait?: number;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ingress_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description The org to act in (default: default). */
                    org?: string;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    overview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description The org to act in (default: default). */
                    org?: string;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    project_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    description?: string;
                    /** @description Default [production]. */
                    environments?: string[];
                    name: string;
                    /** @description The org to act in (default: default). */
                    org?: string;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    project_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @description The org to act in (default: default). */
                    org?: string;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    project_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description The org to act in (default: default). */
                    org?: string;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    sandbox_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description The org to act in (default: default). */
                    org?: string;
                    /** @description The service spec: an object, or YAML text. */
                    spec: unknown;
                    /** @description Run readiness checks (default true). */
                    wait_ready?: boolean;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    sandbox_exec: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    argv: string[];
                    cwd?: string;
                    env?: {
                        [key: string]: string;
                    };
                    name: string;
                    /** @description The org to act in (default: default). */
                    org?: string;
                    /** @description Text fed to the command's stdin. */
                    stdin?: string;
                    /** @description Kill after this long, e.g. 30s (default 10m). */
                    timeout?: string;
                    user?: string;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    sandbox_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    labels?: string[];
                    /** @description The org to act in (default: default). */
                    org?: string;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    sandbox_remove: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @description The org to act in (default: default). */
                    org?: string;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    secret_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Where it is stored (default: local). */
                    driver?: string;
                    labels?: {
                        [key: string]: string;
                    };
                    /** @description Secret name: 1-128 of [A-Za-z0-9_.-], not starting with '.'. */
                    name: string;
                    /** @description The org (default: default). */
                    org?: string;
                    /** @description The value, base64. */
                    value: string;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    secret_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Secret name: 1-128 of [A-Za-z0-9_.-], not starting with '.'. */
                    name: string;
                    /** @description The org (default: default). */
                    org?: string;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    secret_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Secret name: 1-128 of [A-Za-z0-9_.-], not starting with '.'. */
                    name: string;
                    /** @description The org (default: default). */
                    org?: string;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    secret_inspect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Secret name: 1-128 of [A-Za-z0-9_.-], not starting with '.'. */
                    name: string;
                    /** @description The org (default: default). */
                    org?: string;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    secret_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description The org (default: default). */
                    org?: string;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    secret_recipients: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description The org (default: default). */
                    org?: string;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    secret_reencrypt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Every org. */
                    all?: boolean;
                    /** @description The org (default: default). */
                    org?: string;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    secret_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description A store name, or a driver reference a stack uses. */
                    name: string;
                    /** @description The org (default: default). */
                    org?: string;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    secret_resolve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description The org (default: default). */
                    org?: string;
                    /** @description Top-level compose secrets, by key. */
                    secrets: Record<string, never>;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    secret_set: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Secret name: 1-128 of [A-Za-z0-9_.-], not starting with '.'. */
                    name: string;
                    /** @description The org (default: default). */
                    org?: string;
                    /** @description The value, base64. */
                    value: string;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    server_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description The org to act in (default: default). */
                    org?: string;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stack_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @description The org to act in (default: default). */
                    org?: string;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stack_deploy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Host directory relative bind paths resolve against. Remote callers: must be under a --bind-root. */
                    base_dir?: string;
                    /** @description The compose file, as YAML text. ${VAR} is filled from `vars` only. */
                    compose: string;
                    /** @description Only report what would change. */
                    dry_run?: boolean;
                    /** @description Stack name: [a-z0-9-], starts with a letter, at most 30 characters. */
                    name: string;
                    /** @description The org to act in (default: default). */
                    org?: string;
                    /** @description Values of `file:`/`environment:` secrets by top-level secret name. They are stored in the org's store as <stack>_<name>; `external`, `age` and `driver` secrets need none. */
                    secrets?: {
                        [key: string]: string;
                    };
                    /** @description How long wait may take, e.g. 5m (default 10m). */
                    timeout?: string;
                    /** @description Variables for ${VAR} and for secrets with `environment:`. */
                    vars?: {
                        [key: string]: string;
                    };
                    /** @description Wait until every service converges, pauses or fails (default false). */
                    wait?: boolean;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stack_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description The org to act in (default: default). */
                    org?: string;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stack_logs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Default 200. */
                    lines?: number;
                    name: string;
                    /** @description The org to act in (default: default). */
                    org?: string;
                    service: string;
                    /** @description One replica only. */
                    slot?: number;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stack_redeploy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @description The org to act in (default: default). */
                    org?: string;
                    service: string;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stack_remove: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @description The org to act in (default: default). */
                    org?: string;
                    volumes?: boolean;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stack_rollback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @description The org to act in (default: default). */
                    org?: string;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stack_scale: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @description The org to act in (default: default). */
                    org?: string;
                    replicas: number;
                    service: string;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stack_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @description The org to act in (default: default). */
                    org?: string;
                };
            };
        };
        responses: {
            /** @description The tool's result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: unknown;
                    };
                };
            };
            /** @description An error: {error, message, data} */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
