// Writes src/ea-ramps.css: ordered-dither (Bayer 8x8) ramps as SVG masks, in
// 2px cells, for the Execution Associates theme's CSS-only dithered fades
// (meter tails, the glow on a dialog's top edge, the sign-in panel's feathered
// edge). The same threshold matrix the page's WebGL layer (lib/texture-gl.ts)
// uses. Run: bun scripts/dither-ramps.ts
import { writeFileSync } from "node:fs";

function bayer(n: number): number[][] {
  if (n === 2) return [[0, 2], [3, 1]];
  const b = bayer(n / 2);
  const m = b.length;
  const out: number[][] = Array.from({ length: n }, () => Array(n).fill(0));
  for (let y = 0; y < m; y++)
    for (let x = 0; x < m; x++) {
      out[y][x] = 4 * b[y][x];
      out[y][x + m] = 4 * b[y][x] + 2;
      out[y + m][x] = 4 * b[y][x] + 3;
      out[y + m][x + m] = 4 * b[y][x] + 1;
    }
  return out;
}
const B = bayer(8);
const thr = (x: number, y: number) => (B[y & 7][x & 7] + 0.5) / 64;

/** A ramp `cells` long (opaque at 0, clear at the end), 8 cells across, as runs of lit cells. */
function ramp(cells: number, vertical: boolean): string {
  let d = "";
  for (let across = 0; across < 8; across++) {
    let run = -1;
    for (let i = 0; i <= cells; i++) {
      const on = i < cells && 1 - (i + 0.5) / cells > thr(vertical ? across : i, vertical ? i : across);
      if (on && run < 0) run = i;
      if (!on && run >= 0) {
        d += vertical ? `M${across} ${run}h1v${i - run}h-1z` : `M${run} ${across}h${i - run}v1h-${i - run}z`;
        run = -1;
      }
    }
  }
  const w = vertical ? 8 : cells;
  const h = vertical ? cells : 8;
  const svg = `<svg xmlns='http://www.w3.org/2000/svg' width='${w * 2}' height='${h * 2}' viewBox='0 0 ${w} ${h}' shape-rendering='crispEdges'><path d='${d}'/></svg>`;
  return `url("data:image/svg+xml,${svg.replace(/</g, "%3C").replace(/>/g, "%3E").replace(/#/g, "%23")}")`;
}

const css = `/* Generated by scripts/dither-ramps.ts; do not edit. */
:root {
  --ea-ramp-x-s: ${ramp(24, false)}; /* 48px long, 16px tall tile */
  --ea-ramp-x-l: ${ramp(64, false)}; /* 128px long */
  --ea-ramp-y-s: ${ramp(24, true)}; /* 48px tall, 16px wide tile */
  --ea-ramp-y-l: ${ramp(64, true)}; /* 128px tall */
}
`;
writeFileSync(new URL("../src/ea-ramps.css", import.meta.url), css);
