"""TypedDicts for the isb spec format.

Generated by scripts/gen_types.py from `isb schema`. Do not edit by hand.
"""

from __future__ import annotations

from typing import Literal, Mapping, Optional, Sequence, TypedDict, Union

BoolOrString = Union[bool, str]
Scalar = Union[str, bool, int, float]
Command = Union[str, Sequence[Scalar]]
DependCondition = Literal["service_started", "service_healthy"]
FailureAction = Literal["pause", "rollback", "continue"]
IdmapMode = Literal["auto", "none", "always"]
InstanceType = Literal["container", "virtual-machine", "vm"]
IntOrString = Union[int, str]
MapOrList = Union[Mapping[str, Scalar], Sequence[str]]
MountType = Literal["bind", "volume"]
PortBind = Literal["host", "guest"]
RestartCondition = Literal["none", "on-failure", "any"]
RestartMode = Literal["no", "always", "on-failure", "unless-stopped"]
UpdateOrder = Literal["stop-first", "start-first"]


class Dependency(TypedDict, total=False):
    condition: DependCondition


class Deploy(TypedDict, total=False):
    """docker's `deploy:`, for `isb stack deploy`."""
    #: Labels for the service's instances, merged over `labels`.
    labels: MapOrList
    #: Only `replicated`.
    mode: Optional[str]
    #: Number of instances. Default 1. `isb up` handles at most 1.
    replicas: Optional[int]
    #: `limits.cpus` (whole CPUs) and `limits.memory`: the same as `cpus` and
    #: `mem_limit`.
    resources: Optional[Resources]
    #: When the daemon restarts an instance whose app failed.
    restart_policy: Optional[RestartPolicy]
    #: How a rollback is rolled out. Default: like `update_config`.
    rollback_config: Optional[UpdateConfig]
    #: How a changed service is rolled out.
    update_config: Optional[UpdateConfig]


class _EnvValueSecretRequired(TypedDict):
    #: A top-level secret's key.
    secret: str


class EnvValueSecret(_EnvValueSecretRequired, total=False):
    pass


class ExecSpec(TypedDict, total=False):
    """The `exec:` block of a service: exec defaults with no docker equivalent."""
    #: Environment for exec only (merged over `environment`, never stored in
    #: the instance).
    env: MapOrList
    #: Run argv through the user's login shell (`$SHELL -l -c 'exec "$@"'`), so
    #: profile scripts run. argv is still passed as separate arguments.
    login: BoolOrString


class Healthcheck(TypedDict, total=False):
    """docker compose's `healthcheck:`. Durations are strings (`30s`, `1m30s`)."""
    #: Turn off a healthcheck set in another file.
    disable: BoolOrString
    #: Time between checks. Default `30s`.
    interval: Optional[IntOrString]
    #: Consecutive failures before unhealthy. Default 3.
    retries: Optional[int]
    #: Time between checks during `start_period`. Default `5s`.
    start_interval: Optional[IntOrString]
    #: Grace after a start during which failures do not count. Default `0s`.
    start_period: Optional[IntOrString]
    #: `[CMD, argv...]`, `[CMD-SHELL, "a shell line"]`, a plain string (a shell
    #: line), or `[NONE]`. Runs in the guest as the service's `user`.
    test: Optional[Command]
    #: One check's deadline. Default `30s`.
    timeout: Optional[IntOrString]


class IdmapMap(TypedDict, total=False):
    guest_gid: int
    guest_uid: int
    host_gid: int
    host_uid: int
    mode: IdmapMode


class _IdmapRawRequired(TypedDict):
    #: Value for `raw.idmap`, verbatim.
    raw: str


class IdmapRaw(_IdmapRawRequired, total=False):
    pass


class NamedVolumeSpec(TypedDict, total=False):
    """A named custom storage volume."""
    #: Volume config keys (e.g. `size: 10GiB`), applied only at creation.
    config: Mapping[str, Scalar]
    #: The volume must already exist; isb never creates it.
    external: BoolOrString
    #: The incus volume name. Default: `<project>_<key>`, or the key itself
    #: for an `external` volume.
    name: Optional[str]
    #: Storage pool. `auto` (default) means the same pool the sandbox uses
    #: (`storage`), resolved the same way.
    pool: Optional[str]


class _PortMappingRequired(TypedDict):
    #: Port on the host. A range (`5173-5223`) with a single `target` takes the
    #: first free port in it.
    published: IntOrString
    #: Port in the guest, or a range as long as `published`'s.
    target: IntOrString


class PortMapping(_PortMappingRequired, total=False):
    """Docker's long port syntax."""
    #: Host address to listen on. Default `127.0.0.1` (docker's is `0.0.0.0`).
    host_ip: Optional[str]
    #: incus device name. Default: `port-host-<published>`.
    name: Optional[str]
    #: Extra proxy device properties (`proxy_protocol`, ...), verbatim.
    options: Mapping[str, Scalar]
    #: `tcp` (default) or `udp`.
    protocol: Optional[str]


class _ProxyPortRequired(TypedDict):
    #: Connect address, same forms as `listen`. The host defaults to 127.0.0.1
    #: (0.0.0.0 for a VM, which lets incus find the VM's address).
    connect: IntOrString
    #: Listen address: `5173`, `HOST:5173`, `5173/udp`, or the full
    #: `tcp:HOST:PORT` / `udp:HOST:PORT` / `unix:PATH`. The protocol defaults
    #: to tcp and the host to 127.0.0.1.
    listen: IntOrString


class ProxyPort(_ProxyPortRequired, total=False):
    """An incus proxy written out: either direction, any address incus takes."""
    #: `host` (default): listen on the host, connect in the guest. `guest`:
    #: listen in the guest, connect on the host (reach a host service).
    bind: PortBind
    #: incus device name. Default: `port-<bind>-<listen port>`.
    name: Optional[str]
    #: Extra proxy device properties (`nat`, `proxy_protocol`, ...), verbatim.
    options: Mapping[str, Scalar]


class _ReadyCheckUserExistsRequired(TypedDict):
    user_exists: str


class ReadyCheckUserExists(_ReadyCheckUserExistsRequired, total=False):
    """`getent passwd <user>` succeeds in the guest."""


class _ReadyCheckPathWritableRequired(TypedDict):
    path_writable: str


class ReadyCheckPathWritable(_ReadyCheckPathWritableRequired, total=False):
    """The path is writable by the service's `user` (else root)."""


class _ReadyCheckCommandRequired(TypedDict):
    command: Sequence[str]


class ReadyCheckCommand(_ReadyCheckCommandRequired, total=False):
    """This argv exits 0 in the guest (run as root)."""


class ResourceLimits(TypedDict, total=False):
    cpus: Optional[IntOrString]
    memory: Optional[IntOrString]


class Resources(TypedDict, total=False):
    limits: Optional[ResourceLimits]


class RestartPolicy(TypedDict, total=False):
    #: `none`, `on-failure` or `any` (default).
    condition: Optional[RestartCondition]
    #: Wait before restarting. Default `5s`.
    delay: Optional[IntOrString]
    #: Give up after this many restarts within `window`. Default: never.
    max_attempts: Optional[int]
    #: The window `max_attempts` counts in. Default: forever.
    window: Optional[IntOrString]


class SandboxSpec(TypedDict, total=False):
    """Everything about one sandbox: a compose service."""
    #: The sandbox's main command, run by a foreground `isb up` once the
    #: sandbox is ready, as `user` in `working_dir`. Its output is streamed,
    #: and `up` stops the sandbox when every command has exited. A list is
    #: argv; a string is split like a shell would split it, without running
    #: one. Never part of the instance, so changing it is not drift.
    command: Optional[Command]
    #: incus instance name: at most 63 characters of `[a-z0-9-]` (case-insensitive),
    #: starting with a letter. In a compose file it defaults to `<project>-<service>`.
    container_name: Optional[str]
    #: Number of CPUs (`limits.cpu`), a whole number like `8`.
    cpus: Optional[IntOrString]
    #: CPUs to pin to (`limits.cpu`), e.g. `0-3` or `0,2`. Excludes `cpus`.
    cpuset: Optional[IntOrString]
    #: Services to bring up first: a list, or a map to `{condition:
    #: service_started | service_healthy}`.
    depends_on: DependsOnRepr
    #: Replicas, rolling updates and restart policy for `isb stack deploy`.
    deploy: Optional[Deploy]
    #: OCI images only: the entrypoint, run with `command` as its arguments.
    #: On an OCI image `command` alone replaces the whole command line,
    #: including the image's own entrypoint.
    entrypoint: Optional[Command]
    #: Instance environment (`environment.<KEY>`), seen by every exec: a map, or
    #: a list of `KEY=VALUE`. A plain value is instance config, readable by
    #: anyone who can read the instance. `KEY: {secret: NAME}` delivers the
    #: top-level secret NAME as the variable (docs/secrets.md).
    environment: EnvMapOrList
    #: More exec defaults: an exec-only environment and the login shell.
    exec: ExecSpec
    #: A recurring health test, as in docker compose. `isb stack deploy`
    #: routes traffic only to healthy replicas and replaces unhealthy ones;
    #: `depends_on` can wait for it.
    healthcheck: Optional[Healthcheck]
    #: uid/gid mapping so a host user can write bind mounts. See [`IdmapSpec`].
    idmap: Optional[IdmapSpec]
    #: Image: a local alias or fingerprint (`dev-base`), or `remote:alias` for a
    #: well-known remote (`images:debian/12`, `ubuntu:24.04`). A local alias that
    #: does not exist is an error before anything is created.
    image: str
    #: incus profiles to apply, in order. Default: `[default]`. Fixed at creation.
    incus_profiles: Optional[Sequence[str]]
    #: Labels, stored as `user.<key>` config keys: a map, or a list of
    #: `KEY=VALUE`. Used by `isb ls --label` and `isb prune`. isb never removes
    #: a label it was not told about.
    labels: MapOrList
    #: Memory limit (`limits.memory`): docker units (`512m`, `8g`, bytes) or
    #: incus ones (`8GiB`, `50%`).
    mem_limit: Optional[IntOrString]
    #: Published ports (`[HOST_IP:]PUBLISHED:TARGET[/PROTOCOL]` or the long
    #: form), and incus proxies in either direction (`listen`/`connect`).
    ports: Sequence[PortSpec]
    #: Run privileged (`security.privileged`). Omit to leave the incus default
    #: (unprivileged); `false` pins it explicitly.
    privileged: Optional[BoolOrString]
    #: Extra instance config keys, set verbatim (escape hatch).
    raw_config: Mapping[str, Scalar]
    #: Extra devices, set verbatim (escape hatch). Keys are device names.
    raw_devices: Mapping[str, Mapping[str, Scalar]]
    #: Readiness checks, run in order after every start/ensure. Default:
    #: `[running]` for a container, `[running, agent]` for a VM.
    ready: Optional[Sequence[ReadyCheck]]
    #: Deadline for all readiness checks together, e.g. `90s`. Default: `60s`
    #: for a container, `300s` for a VM.
    ready_timeout: Optional[IntOrString]
    #: `no` (default), `always`, `on-failure` or `unless-stopped`. Anything but
    #: `no` makes the service long-running: the instance starts with the host
    #: (`boot.autostart`), and `command` is supervised inside the guest (a
    #: systemd unit, or the instance itself for an OCI image) instead of being
    #: held open by `isb up`, so it survives isb exiting.
    restart: Optional[RestartMode]
    #: Secrets (top-level `secrets:`) to write under `/run/secrets` in the
    #: guest: names, or `{source, target, uid, gid, mode}`.
    secrets: Sequence[SecretRef]
    #: Storage pool for the root disk. `auto` (default): `incus-zfs` if it exists,
    #: else `default`, else the first pool. Fixed at creation.
    storage: Optional[str]
    #: `container` (default) or `virtual-machine` (`vm`). Fixed at creation.
    type: InstanceType
    #: Guest user for `command`, `isb exec` and `path_writable`: a name
    #: (`dev`), `uid`, `uid:gid` or `name:group`. Default root.
    user: Optional[IntOrString]
    #: Mounts: `SOURCE:TARGET[:OPTIONS]` or the long form. A source starting
    #: with `/`, `.` or `~` is a host path; anything else is a named volume.
    volumes: Sequence[VolumeSpec]
    #: Working directory for `command` and `isb exec`. Default: the user's home.
    working_dir: Optional[str]


class SecretDef(TypedDict, total=False):
    """Where a secret's value comes from. Exactly one source."""
    #: The value, age-encrypted to the daemon's recipients (`isb secret
    #: encrypt`): ASCII-armored, or base64 of the binary format.
    age: Optional[str]
    #: Read through this secrets driver, from `name`.
    driver: Optional[str]
    #: An environment variable of whoever deploys the file (`isb up`, or the
    #: client calling `isb stack deploy`).
    environment: Optional[str]
    #: The secret already exists in the org's secret store (`isb secret
    #: create`), under `name` (default: the key).
    external: BoolOrString
    #: A host file holding the value (relative to the compose file).
    file: Optional[str]
    #: With `external`: the store's name for it. With `driver`: the
    #: driver's reference (a 1Password `op://` path, say).
    name: Optional[str]
    #: With `driver`: how often `isb serve` checks the driver for a new
    #: version (`30m`, `1h`; default 1h). A new version rolls the services
    #: using it.
    refresh: Optional[str]


class _SecretRefRequired(TypedDict):
    #: The top-level secret's key.
    source: str


class SecretRef(_SecretRefRequired, total=False):
    """A service's use of a secret."""
    gid: Optional[int]
    #: Octal mode, e.g. `0400` (default) or `"0440"`.
    mode: Optional[IntOrString]
    #: File name under `/run/secrets`, or an absolute path. Default: `source`.
    target: Optional[str]
    #: Owner in the guest: a uid. Default: the service's numeric `user`, else 0.
    uid: Optional[int]


class UpdateConfig(TypedDict, total=False):
    #: Wait between batches. Default `0s`.
    delay: Optional[IntOrString]
    #: `pause` (default), `rollback` or `continue`.
    failure_action: Optional[FailureAction]
    #: How long a new instance must stay healthy to count as a success.
    #: Default `5s`.
    monitor: Optional[IntOrString]
    #: `stop-first` (default) or `start-first`.
    order: Optional[UpdateOrder]
    #: Instances replaced at a time. Default 1; 0 means all at once.
    parallelism: Optional[int]


class _VolumeMountRequired(TypedDict):
    #: Host path to bind-mount (relative paths resolve against the compose
    #: file's directory, `~` expands, symlinks are resolved), or the key of a
    #: named volume.
    source: str
    #: Absolute path inside the guest.
    target: str


class VolumeMount(_VolumeMountRequired, total=False):
    """The long form of a mount."""
    #: incus device name. Default: derived from the target. Set it to adopt an
    #: existing device under a known name.
    device: Optional[str]
    #: Named volumes only: the volume must already exist; isb never creates it.
    external: BoolOrString
    #: Extra disk device properties (`shift`, `propagation`, ...), verbatim.
    options: Mapping[str, Scalar]
    #: Named volumes only: chown the mount point to this guest user (`dev`,
    #: `dev:dev` or `1000:1000`) after it is attached, plus any root-owned
    #: parents inside that user's home that the mount conjured.
    owner: Optional[IntOrString]
    #: Named volumes only: the storage pool. Default: the top-level volume's
    #: pool, else the sandbox's root pool.
    pool: Optional[str]
    #: Mount read-only.
    read_only: BoolOrString
    #: `bind` (a host path) or `volume` (a named volume). Default: `bind` when
    #: `source` starts with `/`, `.` or `~`, else `volume`.
    type: Optional[MountType]
    #: docker's volume options (`nocopy`).
    volume: VolumeOptions


class VolumeOptions(TypedDict, total=False):
    """docker's `volume:` block of a long-form mount."""
    #: Named volumes only: do not seed an empty volume with what the image has
    #: at `target`. Seeding is docker's default; isb does it in containers
    #: (incus `initial.copy`) when the server supports it.
    nocopy: BoolOrString


class ComposeFile(TypedDict, total=False):
    """A compose file: named volumes plus any number of services, each one
    sandbox. Mirrors docker compose wherever incus allows.
    """
    #: incus project to operate in (default: `default`).
    incus_project: Optional[str]
    #: Project name. Default sandbox names are `<name>-<service>` and named
    #: volumes are `<name>_<volume>`. Defaults to the directory holding the
    #: first compose file.
    name: Optional[str]
    #: Secrets services can mount as files under `/run/secrets`. Values are
    #: read when the file is deployed and never stored in instance config.
    secrets: Mapping[str, SecretDef]
    #: Sandboxes, keyed by service name.
    services: Mapping[str, SandboxSpec]
    #: Named custom storage volumes, created if missing before any sandbox that
    #: uses them. Keys are what services refer to.
    volumes: Mapping[str, NamedVolumeSpec]


class SandboxSpecFields(TypedDict, total=False):
    """SandboxSpec without `container_name` and `image`: the keyword arguments of Sandbox.create."""
    #: The sandbox's main command, run by a foreground `isb up` once the
    #: sandbox is ready, as `user` in `working_dir`. Its output is streamed,
    #: and `up` stops the sandbox when every command has exited. A list is
    #: argv; a string is split like a shell would split it, without running
    #: one. Never part of the instance, so changing it is not drift.
    command: Optional[Command]
    #: Number of CPUs (`limits.cpu`), a whole number like `8`.
    cpus: Optional[IntOrString]
    #: CPUs to pin to (`limits.cpu`), e.g. `0-3` or `0,2`. Excludes `cpus`.
    cpuset: Optional[IntOrString]
    #: Services to bring up first: a list, or a map to `{condition:
    #: service_started | service_healthy}`.
    depends_on: DependsOnRepr
    #: Replicas, rolling updates and restart policy for `isb stack deploy`.
    deploy: Optional[Deploy]
    #: OCI images only: the entrypoint, run with `command` as its arguments.
    #: On an OCI image `command` alone replaces the whole command line,
    #: including the image's own entrypoint.
    entrypoint: Optional[Command]
    #: Instance environment (`environment.<KEY>`), seen by every exec: a map, or
    #: a list of `KEY=VALUE`. A plain value is instance config, readable by
    #: anyone who can read the instance. `KEY: {secret: NAME}` delivers the
    #: top-level secret NAME as the variable (docs/secrets.md).
    environment: EnvMapOrList
    #: More exec defaults: an exec-only environment and the login shell.
    exec: ExecSpec
    #: A recurring health test, as in docker compose. `isb stack deploy`
    #: routes traffic only to healthy replicas and replaces unhealthy ones;
    #: `depends_on` can wait for it.
    healthcheck: Optional[Healthcheck]
    #: uid/gid mapping so a host user can write bind mounts. See [`IdmapSpec`].
    idmap: Optional[IdmapSpec]
    #: incus profiles to apply, in order. Default: `[default]`. Fixed at creation.
    incus_profiles: Optional[Sequence[str]]
    #: Labels, stored as `user.<key>` config keys: a map, or a list of
    #: `KEY=VALUE`. Used by `isb ls --label` and `isb prune`. isb never removes
    #: a label it was not told about.
    labels: MapOrList
    #: Memory limit (`limits.memory`): docker units (`512m`, `8g`, bytes) or
    #: incus ones (`8GiB`, `50%`).
    mem_limit: Optional[IntOrString]
    #: Published ports (`[HOST_IP:]PUBLISHED:TARGET[/PROTOCOL]` or the long
    #: form), and incus proxies in either direction (`listen`/`connect`).
    ports: Sequence[PortSpec]
    #: Run privileged (`security.privileged`). Omit to leave the incus default
    #: (unprivileged); `false` pins it explicitly.
    privileged: Optional[BoolOrString]
    #: Extra instance config keys, set verbatim (escape hatch).
    raw_config: Mapping[str, Scalar]
    #: Extra devices, set verbatim (escape hatch). Keys are device names.
    raw_devices: Mapping[str, Mapping[str, Scalar]]
    #: Readiness checks, run in order after every start/ensure. Default:
    #: `[running]` for a container, `[running, agent]` for a VM.
    ready: Optional[Sequence[ReadyCheck]]
    #: Deadline for all readiness checks together, e.g. `90s`. Default: `60s`
    #: for a container, `300s` for a VM.
    ready_timeout: Optional[IntOrString]
    #: `no` (default), `always`, `on-failure` or `unless-stopped`. Anything but
    #: `no` makes the service long-running: the instance starts with the host
    #: (`boot.autostart`), and `command` is supervised inside the guest (a
    #: systemd unit, or the instance itself for an OCI image) instead of being
    #: held open by `isb up`, so it survives isb exiting.
    restart: Optional[RestartMode]
    #: Secrets (top-level `secrets:`) to write under `/run/secrets` in the
    #: guest: names, or `{source, target, uid, gid, mode}`.
    secrets: Sequence[SecretRef]
    #: Storage pool for the root disk. `auto` (default): `incus-zfs` if it exists,
    #: else `default`, else the first pool. Fixed at creation.
    storage: Optional[str]
    #: `container` (default) or `virtual-machine` (`vm`). Fixed at creation.
    type: InstanceType
    #: Guest user for `command`, `isb exec` and `path_writable`: a name
    #: (`dev`), `uid`, `uid:gid` or `name:group`. Default root.
    user: Optional[IntOrString]
    #: Mounts: `SOURCE:TARGET[:OPTIONS]` or the long form. A source starting
    #: with `/`, `.` or `~` is a host path; anything else is a named volume.
    volumes: Sequence[VolumeSpec]
    #: Working directory for `command` and `isb exec`. Default: the user's home.
    working_dir: Optional[str]


DependsOnRepr = Union[Sequence[str], Mapping[str, Dependency]]
EnvValue = Union[Scalar, EnvValueSecret]
EnvMapOrList = Union[Mapping[str, EnvValue], Sequence[str]]
IdmapSpec = Union[IdmapMode, IdmapMap, IdmapRaw]
PortSpec = Union[str, PortMapping, ProxyPort]
ReadyCheck = Union[Literal["running", "agent", "default_route"], ReadyCheckUserExists, ReadyCheckPathWritable, ReadyCheckCommand]
VolumeSpec = Union[str, VolumeMount]

__all__ = [
    "BoolOrString",
    "Command",
    "ComposeFile",
    "DependCondition",
    "Dependency",
    "DependsOnRepr",
    "Deploy",
    "EnvMapOrList",
    "EnvValue",
    "EnvValueSecret",
    "ExecSpec",
    "FailureAction",
    "Healthcheck",
    "IdmapMap",
    "IdmapMode",
    "IdmapRaw",
    "IdmapSpec",
    "InstanceType",
    "IntOrString",
    "MapOrList",
    "MountType",
    "NamedVolumeSpec",
    "PortBind",
    "PortMapping",
    "PortSpec",
    "ProxyPort",
    "ReadyCheck",
    "ReadyCheckCommand",
    "ReadyCheckPathWritable",
    "ReadyCheckUserExists",
    "ResourceLimits",
    "Resources",
    "RestartCondition",
    "RestartMode",
    "RestartPolicy",
    "SandboxSpec",
    "SandboxSpecFields",
    "Scalar",
    "SecretDef",
    "SecretRef",
    "UpdateConfig",
    "UpdateOrder",
    "VolumeMount",
    "VolumeOptions",
    "VolumeSpec",
]
