"""TypedDicts for the isb spec format.

Generated by scripts/gen_types.py from `isb schema`. Do not edit by hand.
"""

from __future__ import annotations

from typing import Literal, Mapping, Optional, Sequence, TypedDict, Union

BoolOrString = Union[bool, str]
IdmapMode = Literal["auto", "none", "always"]
InstanceType = Literal["container", "virtual-machine", "vm"]
IntOrString = Union[int, str]
PortBind = Literal["host", "guest"]
Scalar = Union[str, bool, int, float]


class ExecDefaults(TypedDict, total=False):
    """Defaults for exec into a sandbox. Per-call options override them."""
    #: Working directory in the guest.
    cwd: Optional[str]
    #: Environment for exec (merged over the instance `env`).
    env: Mapping[str, Scalar]
    #: Run argv through the user's login shell (`$SHELL -l -c 'exec "$@"'`), so
    #: profile scripts run. argv is still passed as separate arguments.
    login: BoolOrString
    #: Guest user: a name (`dev`), `uid`, or `uid:gid`. Names are resolved in the
    #: guest, and set HOME/USER/LOGNAME unless given in env.
    user: Optional[IntOrString]


class IdmapMap(TypedDict, total=False):
    guest_gid: int
    guest_uid: int
    host_gid: int
    host_uid: int
    mode: IdmapMode


class _IdmapRawRequired(TypedDict):
    #: Value for `raw.idmap`, verbatim.
    raw: str


class IdmapRaw(_IdmapRawRequired, total=False):
    pass


class NamedVolumeSpec(TypedDict, total=False):
    """A named custom storage volume."""
    #: Volume config keys (e.g. `size: 10GiB`), applied only at creation.
    config: Mapping[str, Scalar]
    #: The volume must already exist; isb never creates it.
    external: BoolOrString
    #: Storage pool. `auto` (default) means the same pool the sandbox uses
    #: (`storage`), resolved the same way.
    pool: Optional[str]


class _PortSpecRequired(TypedDict):
    #: Connect address, same forms as `listen`. The host defaults to 127.0.0.1
    #: (0.0.0.0 for a VM, which lets incus find the VM's address).
    connect: IntOrString
    #: Listen address: `5173`, `HOST:5173`, `5173/udp`, or the full
    #: `tcp:HOST:PORT` / `udp:HOST:PORT` / `unix:PATH`. The protocol defaults
    #: to tcp and the host to 127.0.0.1.
    listen: IntOrString


class PortSpec(_PortSpecRequired, total=False):
    """An incus proxy device."""
    #: `host` (default): listen on the host. `guest`: listen in the guest.
    bind: PortBind
    #: Device name. Default: `port-<bind>-<listen port>`.
    name: Optional[str]
    #: Extra proxy device properties (`nat`, `proxy_protocol`, ...), verbatim.
    options: Mapping[str, Scalar]
    #: Host-bound TCP/UDP only: if the listen port is taken, try the next one, up
    #: to this many more. The chosen address is printed and a device already
    #: listening anywhere in the range counts as correct.
    search: Optional[IntOrString]


class _ReadyCheckUserExistsRequired(TypedDict):
    user_exists: str


class ReadyCheckUserExists(_ReadyCheckUserExistsRequired, total=False):
    """`getent passwd <user>` succeeds in the guest."""


class _ReadyCheckPathWritableRequired(TypedDict):
    path_writable: str


class ReadyCheckPathWritable(_ReadyCheckPathWritableRequired, total=False):
    """The path is writable by the exec user (`exec.user`, else root)."""


class _ReadyCheckCommandRequired(TypedDict):
    command: Sequence[str]


class ReadyCheckCommand(_ReadyCheckCommandRequired, total=False):
    """This argv exits 0 in the guest (run as root)."""


class SandboxSpec(TypedDict, total=False):
    """Everything about one sandbox."""
    #: The sandbox's main command, run by a foreground `isb up` once the
    #: sandbox is ready, with the `exec` defaults. Its output is streamed, and
    #: `up` stops the sandbox when every command has exited. argv form: nothing
    #: is joined into a shell string. Never part of the instance, so changing
    #: it is not drift.
    command: Optional[Sequence[Scalar]]
    #: CPU limit (`limits.cpu`): a count like `8` or a set like `0-3`.
    cpus: Optional[IntOrString]
    #: Instance environment (`environment.<KEY>`), seen by every exec. Not for
    #: secrets: it is plain instance config, readable by anyone who can read the
    #: instance.
    env: Mapping[str, Scalar]
    #: Defaults for `exec` into this sandbox (user, cwd, env, login shell).
    exec: ExecDefaults
    #: uid/gid mapping so a host user can write bind mounts. See [`IdmapSpec`].
    idmap: Optional[IdmapSpec]
    #: Image: a local alias or fingerprint (`dev-base`), or `remote:alias` for a
    #: well-known remote (`images:debian/12`, `ubuntu:24.04`). A local alias that
    #: does not exist is an error before anything is created.
    image: str
    #: Labels, stored as `user.<key>` config keys. Used by `isb ls --label` and
    #: `isb prune`. isb never removes a label it was not told about.
    labels: Mapping[str, Scalar]
    #: Memory limit (`limits.memory`), e.g. `8GiB`.
    memory: Optional[IntOrString]
    #: incus instance name: at most 63 characters of `[a-z0-9-]` (case-insensitive),
    #: starting with a letter. In a compose file it defaults to `<project>-<service>`.
    name: Optional[str]
    #: Proxy devices (port forwards), in either direction.
    ports: Sequence[PortSpec]
    #: Run privileged (`security.privileged`). Omit to leave the incus default
    #: (unprivileged); `false` pins it explicitly.
    privileged: Optional[BoolOrString]
    #: Profiles to apply, in order. Default: `[default]`. Fixed at creation.
    profiles: Optional[Sequence[str]]
    #: Extra instance config keys, set verbatim (escape hatch).
    raw_config: Mapping[str, Scalar]
    #: Extra devices, set verbatim (escape hatch). Keys are device names.
    raw_devices: Mapping[str, Mapping[str, Scalar]]
    #: Readiness checks, run in order after every start/ensure. Default:
    #: `[running]` for a container, `[running, agent]` for a VM.
    ready: Optional[Sequence[ReadyCheck]]
    #: Deadline for all readiness checks together, e.g. `90s`. Default: `60s`
    #: for a container, `300s` for a VM.
    ready_timeout: Optional[IntOrString]
    #: Storage pool for the root disk. `auto` (default): `incus-zfs` if it exists,
    #: else `default`, else the first pool. Fixed at creation.
    storage: Optional[str]
    #: `container` (default) or `virtual-machine` (`vm`). Fixed at creation.
    type: InstanceType
    #: Mounts, keyed by the absolute path inside the guest.
    volumes: Mapping[str, VolumeSpec]


class VolumeSpec(TypedDict, total=False):
    """A mount. Exactly one of `bind` or `named`."""
    #: Host path to bind-mount. Relative paths resolve against the compose file's
    #: directory; `~` expands; symlinks are resolved.
    bind: Optional[str]
    #: Device name. Default: derived from the guest path. Set it to adopt an
    #: existing device under a known name.
    device: Optional[str]
    #: Named volumes only: the volume must already exist; isb never creates it.
    external: BoolOrString
    #: Named custom storage volume to mount (created if missing unless declared
    #: `external`).
    named: Optional[str]
    #: Extra disk device properties (`shift`, `propagation`, ...), verbatim.
    options: Mapping[str, Scalar]
    #: Named volumes only: chown the mount point to this guest user (`dev`,
    #: `dev:dev` or `1000:1000`) after it is attached, plus any root-owned
    #: parents inside that user's home that the mount conjured.
    owner: Optional[IntOrString]
    #: Pool of the named volume. Default: the top-level volume's pool, else `auto`.
    pool: Optional[str]
    #: Mount read-only.
    readonly: BoolOrString


class ComposeFile(TypedDict, total=False):
    """A compose-style file: named volumes plus any number of sandboxes."""
    #: Project name. Default sandbox names are `<name>-<service>`. Defaults to
    #: the directory holding the first compose file.
    name: Optional[str]
    #: incus project to operate in (default: `default`).
    project: Optional[str]
    #: Sandboxes, keyed by service name.
    sandboxes: Mapping[str, SandboxSpec]
    #: Named custom storage volumes, created if missing before any sandbox that
    #: uses them. Keys are volume names.
    volumes: Mapping[str, NamedVolumeSpec]


class SandboxSpecFields(TypedDict, total=False):
    """SandboxSpec without `name` and `image`: the keyword arguments of Sandbox.create."""
    #: The sandbox's main command, run by a foreground `isb up` once the
    #: sandbox is ready, with the `exec` defaults. Its output is streamed, and
    #: `up` stops the sandbox when every command has exited. argv form: nothing
    #: is joined into a shell string. Never part of the instance, so changing
    #: it is not drift.
    command: Optional[Sequence[Scalar]]
    #: CPU limit (`limits.cpu`): a count like `8` or a set like `0-3`.
    cpus: Optional[IntOrString]
    #: Instance environment (`environment.<KEY>`), seen by every exec. Not for
    #: secrets: it is plain instance config, readable by anyone who can read the
    #: instance.
    env: Mapping[str, Scalar]
    #: Defaults for `exec` into this sandbox (user, cwd, env, login shell).
    exec: ExecDefaults
    #: uid/gid mapping so a host user can write bind mounts. See [`IdmapSpec`].
    idmap: Optional[IdmapSpec]
    #: Labels, stored as `user.<key>` config keys. Used by `isb ls --label` and
    #: `isb prune`. isb never removes a label it was not told about.
    labels: Mapping[str, Scalar]
    #: Memory limit (`limits.memory`), e.g. `8GiB`.
    memory: Optional[IntOrString]
    #: Proxy devices (port forwards), in either direction.
    ports: Sequence[PortSpec]
    #: Run privileged (`security.privileged`). Omit to leave the incus default
    #: (unprivileged); `false` pins it explicitly.
    privileged: Optional[BoolOrString]
    #: Profiles to apply, in order. Default: `[default]`. Fixed at creation.
    profiles: Optional[Sequence[str]]
    #: Extra instance config keys, set verbatim (escape hatch).
    raw_config: Mapping[str, Scalar]
    #: Extra devices, set verbatim (escape hatch). Keys are device names.
    raw_devices: Mapping[str, Mapping[str, Scalar]]
    #: Readiness checks, run in order after every start/ensure. Default:
    #: `[running]` for a container, `[running, agent]` for a VM.
    ready: Optional[Sequence[ReadyCheck]]
    #: Deadline for all readiness checks together, e.g. `90s`. Default: `60s`
    #: for a container, `300s` for a VM.
    ready_timeout: Optional[IntOrString]
    #: Storage pool for the root disk. `auto` (default): `incus-zfs` if it exists,
    #: else `default`, else the first pool. Fixed at creation.
    storage: Optional[str]
    #: `container` (default) or `virtual-machine` (`vm`). Fixed at creation.
    type: InstanceType
    #: Mounts, keyed by the absolute path inside the guest.
    volumes: Mapping[str, VolumeSpec]


IdmapSpec = Union[IdmapMode, IdmapMap, IdmapRaw]
ReadyCheck = Union[Literal["running", "agent", "default_route"], ReadyCheckUserExists, ReadyCheckPathWritable, ReadyCheckCommand]

__all__ = [
    "BoolOrString",
    "ComposeFile",
    "ExecDefaults",
    "IdmapMap",
    "IdmapMode",
    "IdmapRaw",
    "IdmapSpec",
    "InstanceType",
    "IntOrString",
    "NamedVolumeSpec",
    "PortBind",
    "PortSpec",
    "ReadyCheck",
    "ReadyCheckCommand",
    "ReadyCheckPathWritable",
    "ReadyCheckUserExists",
    "SandboxSpec",
    "SandboxSpecFields",
    "Scalar",
    "VolumeSpec",
]
