#!/usr/bin/env python3
"""Generate src/isb/_spec.py (TypedDicts) from the isb JSON Schema.

Stdlib only, so the output is stdlib only too.

    python3 scripts/gen_types.py                  # runs `$ISB_BIN schema` (else `isb schema`)
    python3 scripts/gen_types.py --schema s.json  # from a saved schema
    python3 scripts/gen_types.py --check          # exit 1 if _spec.py is stale
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Any

OUT = Path(__file__).resolve().parent.parent / "src" / "isb" / "_spec.py"

HEADER = '''\
"""TypedDicts for the isb spec format.

Generated by scripts/gen_types.py from `isb schema`. Do not edit by hand.
"""

from __future__ import annotations

from typing import Literal, Mapping, Optional, Sequence, TypedDict, Union

'''

# Fields of SandboxSpec that Sandbox.create takes as its own arguments.
SPEC_FIELDS_EXCLUDE = ("container_name", "image")
SPEC_FIELDS_DOC = "SandboxSpec without `container_name` and `image`: the keyword arguments of Sandbox.create."


def first_paragraph(desc: str | None) -> list[str]:
    lines: list[str] = []
    for line in (desc or "").strip().splitlines():
        if not line.strip():
            break
        lines.append(line.rstrip())
    return lines


def ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def camel(s: str) -> str:
    return "".join(p[:1].upper() + p[1:] for p in s.replace("-", "_").split("_"))


class Gen:
    def __init__(self, schema: dict[str, Any]) -> None:
        self.defs: dict[str, Any] = dict(schema.get("$defs", {}))
        root = {k: v for k, v in schema.items() if not k.startswith("$")}
        self.defs[schema.get("title", "ComposeFile")] = root
        self.typeddicts: dict[str, str] = {}
        self.aliases: dict[str, tuple[str, set[str]]] = {}
        self.order: list[str] = []

    def type_of(self, s: dict[str, Any], hint: str) -> tuple[str, set[str]]:
        """Python type expression for a schema, plus alias names it uses."""
        if "$ref" in s:
            n = ref_name(s["$ref"])
            return n, {n}
        if "const" in s:
            return f"Literal[{json.dumps(s['const'])}]", set()
        if "enum" in s:
            return "Literal[" + ", ".join(json.dumps(e) for e in s["enum"]) + "]", set()
        for key in ("anyOf", "oneOf"):
            if key in s:
                parts: list[str] = []
                deps: set[str] = set()
                nullable = False
                for i, sub in enumerate(s[key]):
                    if sub.get("type") == "null":
                        nullable = True
                        continue
                    t, d = self.type_of(sub, self.variant_name(hint, sub, i))
                    parts.append(t)
                    deps |= d
                lits = [p[8:-1] for p in parts if p.startswith("Literal[")]
                others = [p for p in parts if not p.startswith("Literal[")]
                if len(lits) > 1:
                    parts = ["Literal[" + ", ".join(lits) + "]", *others]
                t = parts[0] if len(parts) == 1 else "Union[" + ", ".join(parts) + "]"
                return (f"Optional[{t}]" if nullable else t), deps
        ty = s.get("type")
        if isinstance(ty, list):
            non_null = [x for x in ty if x != "null"]
            t, d = self.type_of({**s, "type": non_null[0]}, hint)
            return (f"Optional[{t}]" if "null" in ty else t), d
        if ty == "string":
            return "str", set()
        if ty == "boolean":
            return "bool", set()
        if ty == "integer":
            return "int", set()
        if ty == "number":
            return "float", set()
        if ty == "array":
            t, d = self.type_of(s.get("items", {}), hint + "Item")
            return f"Sequence[{t}]", d
        if ty == "object":
            if "properties" in s:
                self.typeddict(hint, s)
                return hint, {hint}
            ap = s.get("additionalProperties")
            if isinstance(ap, dict):
                t, d = self.type_of(ap, hint + "Value")
                return f"Mapping[str, {t}]", d
            return "Mapping[str, object]", set()
        return "object", set()

    def variant_name(self, hint: str, sub: dict[str, Any], i: int) -> str:
        req = sub.get("required") or []
        if len(req) == 1:
            return hint + camel(req[0])
        return f"{hint}{i}"

    def typeddict(self, name: str, s: dict[str, Any], exclude: tuple[str, ...] = (), doc: str | None = None) -> None:
        if name in self.typeddicts:
            return
        self.typeddicts[name] = ""  # reserve (recursion)
        required = set(s.get("required", []))
        req_lines: list[str] = []
        opt_lines: list[str] = []
        for field, sub in s.get("properties", {}).items():
            if field in exclude:
                continue
            t, _ = self.type_of(sub, name + camel(field))
            line = f"    {field}: {t}"
            desc = first_paragraph(sub.get("description"))
            if desc:
                line = "".join(f"    #: {d}\n" for d in desc) + line
            (req_lines if field in required else opt_lines).append(line)
        lines = [doc] if doc is not None else first_paragraph(s.get("description"))
        doc_line = ""
        if lines:
            doc_line = '    """' + "\n    ".join(lines) + ('\n    """\n' if len(lines) > 1 else '"""\n')
        if req_lines:
            base = f"_{name}Required"
            text = f"class {base}(TypedDict):\n" + "\n".join(req_lines) + "\n\n\n"
            text += f"class {name}({base}, total=False):\n{doc_line}"
            text += "\n".join(opt_lines) + "\n" if opt_lines else ("" if doc_line else "    pass\n")
        else:
            text = f"class {name}(TypedDict, total=False):\n{doc_line}"
            text += "\n".join(opt_lines) + "\n" if opt_lines else ("" if doc_line else "    pass\n")
        self.typeddicts[name] = text
        self.order.append(name)

    def run(self) -> str:
        for name, s in self.defs.items():
            if s.get("type") == "object" and "properties" in s:
                self.typeddict(name, s)
            else:
                t, deps = self.type_of(s, name)
                if t != name:
                    self.aliases[name] = (t, deps)
        spec = self.defs["SandboxSpec"]
        self.typeddict("SandboxSpecFields", spec, exclude=SPEC_FIELDS_EXCLUDE, doc=SPEC_FIELDS_DOC)

        out = [HEADER]
        # Aliases that do not reference TypedDicts first, in dependency order;
        # TypedDict bodies are lazy (postponed annotations); then the rest.
        emitted: set[str] = set()

        def emit_alias(n: str) -> None:
            if n in emitted or n not in self.aliases:
                return
            t, deps = self.aliases[n]
            for d in sorted(deps):
                emit_alias(d)
            emitted.add(n)
            out.append(f"{n} = {t}\n")

        simple = [n for n, (_, deps) in self.aliases.items() if not deps & set(self.typeddicts)]
        for n in sorted(simple):
            emit_alias(n)
        out.append("\n")
        for n in self.order:
            out.append("\n" + self.typeddicts[n] + "\n")
        rest = [n for n in self.aliases if n not in emitted]
        if rest:
            out.append("\n")
            for n in sorted(rest):
                emit_alias(n)
        names = sorted(set(self.aliases) | set(self.order))
        out.append("\n__all__ = [\n" + "".join(f'    "{n}",\n' for n in names) + "]\n")
        return "".join(out).replace("\n\n\n\n", "\n\n\n")


def load_schema(path: str | None) -> dict[str, Any]:
    if path:
        text = Path(path).read_text()
    else:
        isb = os.environ.get("ISB_BIN") or "isb"
        text = subprocess.run([isb, "schema"], check=True, capture_output=True, text=True).stdout
    schema: dict[str, Any] = json.loads(text)
    return schema


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--schema", help="read the schema from this file instead of `isb schema`")
    ap.add_argument("--check", action="store_true", help="fail if the committed file differs")
    ap.add_argument("--out", default=str(OUT))
    a = ap.parse_args()
    text = Gen(load_schema(a.schema)).run()
    out = Path(a.out)
    if a.check:
        if not out.exists() or out.read_text() != text:
            print(f"{out} is stale; run scripts/gen_types.py", file=sys.stderr)
            return 1
        return 0
    out.write_text(text)
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
