// "New database" in a project environment: engine, version, name, and
// optionally the database and user names and a published port
// (database_create). Credentials are generated by the daemon.
import { useQueryClient } from "@tanstack/react-query";
import { Database as DbIcon, Loader2 } from "lucide-react";
import { useState } from "react";
import { useNavigate } from "react-router";
import { toast } from "sonner";
import { callTool } from "@/api/tools";
import { keys } from "@/apps/api";
import { Field, FormError } from "@/components/form";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { errorMessage } from "@/lib/messages";
import { cn } from "@/lib/utils";
import { dbNameProblem, type Engine, ENGINES } from "./api";

export function NewDatabaseDialog({
  org,
  project,
  environment,
  open,
  onOpenChange,
}: {
  org: string;
  project: string;
  environment: string;
  open: boolean;
  onOpenChange: (o: boolean) => void;
}) {
  const qc = useQueryClient();
  const navigate = useNavigate();
  const [engine, setEngine] = useState<Engine>("postgres");
  const [version, setVersion] = useState("");
  const [name, setName] = useState("");
  const [database, setDatabase] = useState("");
  const [user, setUser] = useState("");
  const [publish, setPublish] = useState("");
  const [more, setMore] = useState(false);
  const [touched, setTouched] = useState(false);
  const [pending, setPending] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const info = ENGINES.find((e) => e.id === engine) ?? ENGINES[0];
  const nameErr = dbNameProblem(name);
  const pubErr = publish && !/^(?:\d{1,3}(?:\.\d{1,3}){3}:)?\d{1,5}$/.test(publish.trim()) ? "[IP:]PORT, such as 15432 or 127.0.0.1:15432." : null;
  const redis = engine === "redis";

  const reset = () => {
    setEngine("postgres");
    setVersion("");
    setName("");
    setDatabase("");
    setUser("");
    setPublish("");
    setMore(false);
    setTouched(false);
    setError(null);
  };

  const close = (o: boolean) => {
    if (pending) return;
    onOpenChange(o);
    if (!o) reset();
  };

  const submit = async (e: React.FormEvent) => {
    e.preventDefault();
    setTouched(true);
    if (nameErr || pubErr) return;
    setPending(true);
    setError(null);
    try {
      const args: Record<string, unknown> = { name, project, environment, engine };
      if (version.trim()) args.version = version.trim();
      if (!redis && database.trim()) args.database = database.trim();
      if (!redis && user.trim()) args.user = user.trim();
      if (publish.trim()) args.publish = publish.trim();
      await callTool<unknown, string>("database_create", args, org);
      await qc.invalidateQueries({ queryKey: keys.org(org) });
      toast.success(`Database ${name} created; it is starting`);
      const n = name;
      setPending(false);
      close(false);
      navigate(`/orgs/${encodeURIComponent(org)}/apps/${n}/database`);
    } catch (err) {
      setError(errorMessage(err));
      setPending(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={close}>
      <DialogContent className="max-h-[92svh] overflow-y-auto sm:max-w-2xl">
        <DialogHeader>
          <DialogTitle>New database</DialogTitle>
          <DialogDescription>
            In {project} / {environment}. Its password is generated and kept as the org secret{" "}
            <span className="font-mono">db.{name || "NAME"}.password</span>.
          </DialogDescription>
        </DialogHeader>
        <form onSubmit={submit} className="grid gap-4">
          <div className="grid grid-cols-2 gap-2 sm:grid-cols-5" role="radiogroup" aria-label="Engine">
            {ENGINES.map((x) => (
              <button
                key={x.id}
                type="button"
                role="radio"
                aria-checked={engine === x.id}
                onClick={() => {
                  setEngine(x.id);
                  setVersion("");
                }}
                className={cn(
                  "flex flex-col items-start gap-1 rounded-lg border p-3 text-left text-sm transition-colors focus-visible:ring-[3px] focus-visible:ring-ring/50 focus-visible:outline-none",
                  engine === x.id ? "border-foreground/60 bg-accent" : "hover:bg-accent/60",
                )}
              >
                <DbIcon className="size-4" />
                <span className="font-medium">{x.label}</span>
                <span className="text-xs text-muted-foreground">:{x.port}</span>
              </button>
            ))}
          </div>
          {engine === "mongodb" && (
            <p className="rounded-md border border-warning/40 bg-warning/10 px-3 py-2 text-xs">
              MongoDB 8.0 and 8.2 refuse to start on Linux 6.19 and newer (SERVER-121912). Pick 7.0 on such hosts.
            </p>
          )}
          <FormError>{error}</FormError>
          <div className="grid items-start gap-4 sm:grid-cols-2">
            <Field label="Name" error={touched || name ? nameErr : null} hint="Its service name: other apps here reach it by it.">
              {(id, d) => (
                <Input
                  id={id}
                  aria-describedby={d}
                  autoFocus
                  autoComplete="off"
                  spellCheck={false}
                  value={name}
                  onChange={(e) => setName(e.target.value.toLowerCase())}
                  placeholder={engine === "postgres" ? "pg" : engine}
                />
              )}
            </Field>
            <Field label="Version" hint={`The official image's tag; default ${info.version}.`}>
              {(id, d) => (
                <>
                  <Input id={id} aria-describedby={d} list={`${id}-v`} spellCheck={false} value={version} onChange={(e) => setVersion(e.target.value)} placeholder={info.version} />
                  <datalist id={`${id}-v`}>
                    {info.versions.map((v) => (
                      <option key={v} value={v} />
                    ))}
                  </datalist>
                </>
              )}
            </Field>
          </div>
          {!more ? (
            <Button type="button" variant="link" className="h-auto justify-self-start p-0 text-muted-foreground" onClick={() => setMore(true)}>
              Database name, user and port…
            </Button>
          ) : (
            <div className="grid items-start gap-4 sm:grid-cols-2">
              {!redis && (
                <>
                  <Field label="Database" hint="Made on first start; default the name with - as _.">
                    {(id, d) => <Input id={id} aria-describedby={d} spellCheck={false} value={database} onChange={(e) => setDatabase(e.target.value)} />}
                  </Field>
                  <Field label="User" hint="Default: as the database.">
                    {(id, d) => <Input id={id} aria-describedby={d} spellCheck={false} value={user} onChange={(e) => setUser(e.target.value)} />}
                  </Field>
                </>
              )}
              <Field label="Publish on the host" error={pubErr} hint="Off by default: only apps in the org reach it. [IP:]PORT, address 127.0.0.1 unless given." className="sm:col-span-2">
                {(id, d) => <Input id={id} aria-describedby={d} spellCheck={false} value={publish} onChange={(e) => setPublish(e.target.value)} placeholder="15432" />}
              </Field>
            </div>
          )}
          <DialogFooter>
            <Button type="button" variant="outline" onClick={() => close(false)} disabled={pending}>
              Cancel
            </Button>
            <Button type="submit" disabled={pending}>
              {pending && <Loader2 className="animate-spin" />}
              Create and start
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
