// Regenerate src/spec.ts from the JSON Schema of the compose format.
//
//   ISB_BIN=/path/to/isb bun scripts/gen-types.ts        # runs `isb schema`
//   bun scripts/gen-types.ts schema.json                 # from a saved schema
//
// Uses json-schema-to-typescript (a dev dependency): run it where dev
// dependencies are installed, never on a host that should not execute them.

import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { compile, type JSONSchema } from "json-schema-to-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "src", "spec.ts");

function loadSchema(): JSONSchema {
  const file = process.argv[2];
  if (file) return JSON.parse(readFileSync(file, "utf8"));
  const bin = process.env.ISB_BIN ?? "isb";
  const r = spawnSync(bin, ["schema"], { encoding: "utf8" });
  if (r.status !== 0) {
    throw new Error(`${bin} schema failed: ${r.error ?? r.stderr}`);
  }
  return JSON.parse(r.stdout);
}

// A `$ref` with sibling keywords (usually a field description) makes
// json-schema-to-typescript emit a numbered copy of the referenced type
// (BoolOrString1, ExecDefaults1). Keep only the reference.
function stripRefSiblings(node: unknown): void {
  if (Array.isArray(node)) {
    for (const n of node) stripRefSiblings(n);
    return;
  }
  if (node === null || typeof node !== "object") return;
  const o = node as Record<string, unknown>;
  if (typeof o.$ref === "string") {
    for (const k of Object.keys(o)) if (k !== "$ref") delete o[k];
    return;
  }
  for (const v of Object.values(o)) stripRefSiblings(v);
}

const schema = loadSchema();
stripRefSiblings(schema);
// Name every definition after its key, so each becomes an exported type.
const defs = (schema.$defs ?? {}) as Record<string, JSONSchema>;
for (const [key, def] of Object.entries(defs)) def.title = key;
schema.title = "ComposeFile";

let ts = await compile(schema, "ComposeFile", {
  bannerComment: [
    "// Generated by scripts/gen-types.ts from `isb schema`. Do not edit by hand.",
    "// Field names are exactly those of the compose YAML (docs/reference/compose.md).",
    "",
  ].join("\n"),
  additionalProperties: false,
  unreachableDefinitions: true,
  strictIndexSignatures: false,
  style: { singleQuote: false, semi: true, printWidth: 100 },
});
ts = ts.replace(/\n{3,}/g, "\n\n");
writeFileSync(out, ts);
console.log(`wrote ${out}`);
