// Generated by scripts/gen-types.ts from `isb schema`. Do not edit by hand.
// Field names are exactly those of the compose YAML (docs/reference/compose.md).

/**
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "BoolOrString".
 */
export type BoolOrString = boolean | string;
/**
 * A command: argv, or a string split the way a shell splits words.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "Command".
 */
export type Command = string | Scalar[];
/**
 * A scalar (string, number or boolean) read as a string.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "Scalar".
 */
export type Scalar = string | boolean | number;
/**
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "IntOrString".
 */
export type IntOrString = number | string;
/**
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "DependsOnRepr".
 */
export type DependsOnRepr =
  | string[]
  | {
      [k: string]: Dependency;
    };
/**
 * What a dependency must reach before its dependents start.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "DependCondition".
 */
export type DependCondition = "service_started" | "service_healthy";
/**
 * A map, or docker's list of `KEY=VALUE` strings.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "MapOrList".
 */
export type MapOrList =
  | {
      [k: string]: Scalar;
    }
  | string[];
/**
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "RestartCondition".
 */
export type RestartCondition = "none" | "on-failure" | "any";
/**
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "FailureAction".
 */
export type FailureAction = "pause" | "rollback" | "continue";
/**
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "UpdateOrder".
 */
export type UpdateOrder = "stop-first" | "start-first";
/**
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "EgressSpec".
 */
export type EgressSpec =
  | string
  | string[]
  | {
      /**
       * The hosts the sandbox may reach: `host[:port]`.
       */
      allow?: string[];
      /**
       * Secrets the guest sees only as placeholders.
       */
      secrets?: EgressSecretSpec[];
    };
/**
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "EgressSecretSpec".
 */
export type EgressSecretSpec =
  | string
  | {
      /**
       * The environment variable the guest sees (holding a placeholder).
       */
      env: string;
      /**
       * Hosts the real value may be sent to: `host[:port]`, port 443 by default.
       */
      hosts: string[];
      /**
       * The secret in the org's store (default: the variable's name).
       */
      secret?: string | null;
    };
/**
 * An environment: a map (a value may be `{secret: NAME}`), or docker's
 * list of `KEY=VALUE` strings.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "EnvMapOrList".
 */
export type EnvMapOrList =
  | {
      [k: string]: EnvValue;
    }
  | string[];
/**
 * One `environment` value: a scalar, or a top-level secret delivered as the
 * variable.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "EnvValue".
 */
export type EnvValue =
  | Scalar
  | {
      /**
       * A top-level secret's key.
       */
      secret: string;
    };
/**
 * idmap handling.
 *
 * The usual need is "host uid/gid 1000 must be the guest's uid/gid 1000 so a
 * bind-mounted checkout is writable". Whether that needs `raw.idmap` depends on
 * the host: when root's subordinate id range (in `/etc/subuid`, `/etc/subgid`)
 * already contains the host id, the default map covers it and asking for
 * `raw.idmap` is refused by incus ("Host ID is in the range of subids"); when
 * it does not (a separate `root:1000:1` delegation only permits the mapping),
 * `raw.idmap` is required.
 *
 * Forms:
 * - `auto`: map 1000:1000 ↔ 1000:1000 only where needed (per id, uid and gid
 *   checked separately).
 * - `none`: never set `raw.idmap`.
 * - `always`: always set it for 1000 ↔ 1000.
 * - `{mode: auto|always, host_uid, host_gid, guest_uid, guest_gid}`: other ids.
 * - `{raw: "both 1000 1000"}`: an explicit `raw.idmap` value.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "IdmapSpec".
 */
export type IdmapSpec = IdmapMode | IdmapMap | IdmapRaw;
/**
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "IdmapMode".
 */
export type IdmapMode = "auto" | "none" | "always";
/**
 * A published port, docker style, or an incus proxy in either direction.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "PortSpec".
 */
export type PortSpec = string | PortMapping | ProxyPort;
/**
 * Which side listens.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "PortBind".
 */
export type PortBind = "host" | "guest";
/**
 * A readiness check. "Running" alone is not ready: networking comes up a beat
 * after the instance does.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "ReadyCheck".
 */
export type ReadyCheck =
  | "running"
  | "agent"
  | "default_route"
  | {
      user_exists: string;
    }
  | {
      path_writable: string;
    }
  | {
      command: string[];
    };
/**
 * docker's `restart:`.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "RestartMode".
 */
export type RestartMode = "no" | "always" | "on-failure" | "unless-stopped";
/**
 * Instance type.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "InstanceType".
 */
export type InstanceType = "container" | "virtual-machine" | "vm";
/**
 * A mount: `SOURCE:TARGET[:OPTIONS]` or the long form.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "VolumeSpec".
 */
export type VolumeSpec = string | VolumeMount;
/**
 * What a mount's `source` is.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "MountType".
 */
export type MountType = "bind" | "volume";

/**
 * A compose file: named volumes plus any number of services, each one
 * sandbox. Mirrors docker compose wherever incus allows.
 */
export interface ComposeFile {
  /**
   * incus project to operate in (default: `default`).
   */
  incus_project?: string | null;
  /**
   * Project name. Default sandbox names are `<name>-<service>` and named
   * volumes are `<name>_<volume>`. Defaults to the directory holding the
   * first compose file.
   */
  name?: string | null;
  /**
   * Secrets services can mount as files under `/run/secrets`. Values are
   * read when the file is deployed and never stored in instance config.
   */
  secrets?: {
    [k: string]: SecretDef;
  };
  /**
   * Sandboxes, keyed by service name.
   */
  services?: {
    [k: string]: SandboxSpec;
  };
  /**
   * Named custom storage volumes, created if missing before any sandbox that
   * uses them. Keys are what services refer to.
   */
  volumes?: {
    [k: string]: NamedVolumeSpec;
  };
}
/**
 * Where a secret's value comes from. Exactly one source.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "SecretDef".
 */
export interface SecretDef {
  /**
   * The value, age-encrypted to the daemon's recipients (`isb secret
   * encrypt`): ASCII-armored, or base64 of the binary format.
   */
  age?: string | null;
  /**
   * Read through this secrets driver, from `name`.
   */
  driver?: string | null;
  /**
   * An environment variable of whoever deploys the file (`isb up`, or the
   * client calling `isb stack deploy`).
   */
  environment?: string | null;
  external?: BoolOrString;
  /**
   * A host file holding the value (relative to the compose file).
   */
  file?: string | null;
  /**
   * With `external`: the store's name for it. With `driver`: the
   * driver's reference (a 1Password `op://` path, say).
   */
  name?: string | null;
  /**
   * With `driver`: how often `isb serve` checks the driver for a new
   * version (`30m`, `1h`; default 1h). A new version rolls the services
   * using it.
   */
  refresh?: string | null;
}
/**
 * Everything about one sandbox: a compose service.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "SandboxSpec".
 */
export interface SandboxSpec {
  /**
   * The sandbox's main command, run by a foreground `isb up` once the
   * sandbox is ready, as `user` in `working_dir`. Its output is streamed,
   * and `up` stops the sandbox when every command has exited. A list is
   * argv; a string is split like a shell would split it, without running
   * one. Never part of the instance, so changing it is not drift.
   */
  command?: Command | null;
  /**
   * incus instance name: at most 63 characters of `[a-z0-9-]` (case-insensitive),
   * starting with a letter. In a compose file it defaults to `<project>-<service>`.
   */
  container_name?: string | null;
  /**
   * Number of CPUs (`limits.cpu`), a whole number like `8`.
   */
  cpus?: IntOrString | null;
  /**
   * CPUs to pin to (`limits.cpu`), e.g. `0-3` or `0,2`. Excludes `cpus`.
   */
  cpuset?: IntOrString | null;
  depends_on?: DependsOnRepr;
  /**
   * Replicas, rolling updates and restart policy for `isb stack deploy`.
   */
  deploy?: Deploy | null;
  /**
   * Public hostnames `isb serve`'s ingress routes to this service's
   * replicas (docs/guides/domains.md). Only stacks use them; `isb up` ignores
   * them.
   */
  domains?: DomainSpec[];
  /**
   * Which hostnames the sandbox may reach, and secrets that never enter
   * it (docs/guides/egress.md). `none` denies all network; a list of
   * `host[:port]` (port 443 by default; `*.example.com` for subdomains)
   * denies everything else, public and private; `{allow, secrets}` adds
   * secrets the guest sees only as placeholders, put on the wire towards
   * their approved hosts. Omitted: open egress, as before. Needs
   * `isb serve` running for its proxy.
   */
  egress?: EgressSpec | null;
  /**
   * OCI images only: the entrypoint, run with `command` as its arguments.
   * On an OCI image `command` alone replaces the whole command line,
   * including the image's own entrypoint.
   */
  entrypoint?: Command | null;
  environment?: EnvMapOrList;
  exec?: ExecSpec;
  /**
   * A recurring health test, as in docker compose. `isb stack deploy`
   * routes traffic only to healthy replicas and replaces unhealthy ones;
   * `depends_on` can wait for it.
   */
  healthcheck?: Healthcheck | null;
  /**
   * uid/gid mapping so a host user can write bind mounts. See [`IdmapSpec`].
   */
  idmap?: IdmapSpec | null;
  /**
   * Image: a local alias or fingerprint (`dev-base`), or `remote:alias` for a
   * well-known remote (`images:debian/12`, `ubuntu:24.04`). A local alias that
   * does not exist is an error before anything is created.
   */
  image?: string;
  /**
   * incus profiles to apply, in order. Default: `[default]`. Fixed at creation.
   */
  incus_profiles?: string[] | null;
  labels?: MapOrList;
  /**
   * Memory limit (`limits.memory`): docker units (`512m`, `8g`, bytes) or
   * incus ones (`8GiB`, `50%`).
   */
  mem_limit?: IntOrString | null;
  /**
   * Published ports (`[HOST_IP:]PUBLISHED:TARGET[/PROTOCOL]` or the long
   * form), and incus proxies in either direction (`listen`/`connect`).
   */
  ports?: PortSpec[];
  /**
   * Run privileged (`security.privileged`). Omit to leave the incus default
   * (unprivileged); `false` pins it explicitly.
   */
  privileged?: BoolOrString | null;
  /**
   * Extra instance config keys, set verbatim (escape hatch).
   */
  raw_config?: {
    [k: string]: Scalar;
  };
  /**
   * Extra devices, set verbatim (escape hatch). Keys are device names.
   */
  raw_devices?: {
    [k: string]: {
      [k: string]: Scalar;
    };
  };
  /**
   * Readiness checks, run in order after every start/ensure. Default:
   * `[running]` for a container, `[running, agent]` for a VM.
   */
  ready?: ReadyCheck[] | null;
  /**
   * Deadline for all readiness checks together, e.g. `90s`. Default: `60s`
   * for a container, `300s` for a VM.
   */
  ready_timeout?: IntOrString | null;
  /**
   * `no` (default), `always`, `on-failure` or `unless-stopped`. Anything but
   * `no` makes the service long-running: the instance starts with the host
   * (`boot.autostart`), and `command` is supervised inside the guest (a
   * systemd unit, or the instance itself for an OCI image) instead of being
   * held open by `isb up`, so it survives isb exiting.
   */
  restart?: RestartMode | null;
  /**
   * Secrets (top-level `secrets:`) to write under `/run/secrets` in the
   * guest: names, or `{source, target, uid, gid, mode}`.
   */
  secrets?: SecretRef[];
  /**
   * Storage pool for the root disk. `auto` (default): `incus-zfs` if it exists,
   * else `default`, else the first pool. Fixed at creation.
   */
  storage?: string | null;
  type?: InstanceType;
  /**
   * Guest user for `command`, `isb exec` and `path_writable`: a name
   * (`dev`), `uid`, `uid:gid` or `name:group`. Default root.
   */
  user?: IntOrString | null;
  /**
   * Mounts: `SOURCE:TARGET[:OPTIONS]` or the long form. A source starting
   * with `/`, `.` or `~` is a host path; anything else is a named volume.
   */
  volumes?: VolumeSpec[];
  /**
   * Working directory for `command` and `isb exec`. Default: the user's home.
   */
  working_dir?: string | null;
}
/**
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "Dependency".
 */
export interface Dependency {
  condition?: DependCondition;
}
/**
 * docker's `deploy:`, for `isb stack deploy`.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "Deploy".
 */
export interface Deploy {
  labels?: MapOrList;
  /**
   * Only `replicated`.
   */
  mode?: string | null;
  /**
   * Number of instances. Default 1. `isb up` handles at most 1.
   */
  replicas?: number | null;
  /**
   * `limits.cpus` (whole CPUs) and `limits.memory`: the same as `cpus` and
   * `mem_limit`.
   */
  resources?: Resources | null;
  /**
   * When the daemon restarts an instance whose app failed.
   */
  restart_policy?: RestartPolicy | null;
  /**
   * How a rollback is rolled out. Default: like `update_config`.
   */
  rollback_config?: UpdateConfig | null;
  /**
   * How a changed service is rolled out.
   */
  update_config?: UpdateConfig | null;
}
/**
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "Resources".
 */
export interface Resources {
  limits?: ResourceLimits | null;
}
/**
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "ResourceLimits".
 */
export interface ResourceLimits {
  cpus?: IntOrString | null;
  memory?: IntOrString | null;
}
/**
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "RestartPolicy".
 */
export interface RestartPolicy {
  /**
   * `none`, `on-failure` or `any` (default).
   */
  condition?: RestartCondition | null;
  /**
   * Wait before restarting. Default `5s`.
   */
  delay?: IntOrString | null;
  /**
   * Give up after this many restarts within `window`. Default: never.
   */
  max_attempts?: number | null;
  /**
   * The window `max_attempts` counts in. Default: forever.
   */
  window?: IntOrString | null;
}
/**
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "UpdateConfig".
 */
export interface UpdateConfig {
  /**
   * Wait between batches. Default `0s`.
   */
  delay?: IntOrString | null;
  /**
   * `pause` (default), `rollback` or `continue`.
   */
  failure_action?: FailureAction | null;
  /**
   * How long a new instance must stay healthy to count as a success.
   * Default `5s`.
   */
  monitor?: IntOrString | null;
  /**
   * `stop-first` (default) or `start-first`.
   */
  order?: UpdateOrder | null;
  /**
   * Instances replaced at a time. Default 1; 0 means all at once.
   */
  parallelism?: number | null;
}
/**
 * A hostname (and path) the ingress serves a service on.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "DomainSpec".
 */
export interface DomainSpec {
  /**
   * The hostname, e.g. `app.example.com`; `*.example.com` where the org
   * allows wildcards; or `auto` for a generated
   * `<service>-<stack>-<org>.<ip>.sslip.io` name.
   */
  host: string;
  /**
   * Serve over HTTPS with a certificate the ingress obtains (default
   * true), redirecting plain HTTP to it. `false` serves plain HTTP.
   */
  https?: BoolOrString | null;
  /**
   * Path prefix (default `/`): `/api` matches `/api` and `/api/...`.
   */
  path?: string | null;
  /**
   * The port the service listens on inside its replicas. Not needed with
   * `redirect`.
   */
  port?: number | null;
  /**
   * Answer every request with a permanent redirect (308) to this URL
   * instead of proxying. A URL without a path keeps the request's path
   * and query (`https://example.com`); one with a path is used as is.
   */
  redirect?: string | null;
  strip_prefix?: BoolOrString;
  www_redirect?: BoolOrString;
}
/**
 * The `exec:` block of a service: exec defaults with no docker equivalent.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "ExecSpec".
 */
export interface ExecSpec {
  env?: MapOrList;
  login?: BoolOrString;
}
/**
 * docker compose's `healthcheck:`. Durations are strings (`30s`, `1m30s`).
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "Healthcheck".
 */
export interface Healthcheck {
  disable?: BoolOrString;
  /**
   * Time between checks. Default `30s`.
   */
  interval?: IntOrString | null;
  /**
   * Consecutive failures before unhealthy. Default 3.
   */
  retries?: number | null;
  /**
   * Time between checks during `start_period`. Default `5s`.
   */
  start_interval?: IntOrString | null;
  /**
   * Grace after a start during which failures do not count. Default `0s`.
   */
  start_period?: IntOrString | null;
  /**
   * `[CMD, argv...]`, `[CMD-SHELL, "a shell line"]`, a plain string (a shell
   * line), or `[NONE]`. Runs in the guest as the service's `user`.
   */
  test?: Command | null;
  /**
   * One check's deadline. Default `30s`.
   */
  timeout?: IntOrString | null;
}
/**
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "IdmapMap".
 */
export interface IdmapMap {
  guest_gid?: number;
  guest_uid?: number;
  host_gid?: number;
  host_uid?: number;
  mode?: IdmapMode;
}
/**
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "IdmapRaw".
 */
export interface IdmapRaw {
  /**
   * Value for `raw.idmap`, verbatim.
   */
  raw: string;
}
/**
 * Docker's long port syntax.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "PortMapping".
 */
export interface PortMapping {
  /**
   * Host address to listen on. Default `127.0.0.1` (docker's is `0.0.0.0`).
   */
  host_ip?: string | null;
  /**
   * incus device name. Default: `port-host-<published>`.
   */
  name?: string | null;
  /**
   * Extra proxy device properties (`proxy_protocol`, ...), verbatim.
   */
  options?: {
    [k: string]: Scalar;
  };
  /**
   * `tcp` (default) or `udp`.
   */
  protocol?: string | null;
  published: IntOrString;
  target: IntOrString;
}
/**
 * An incus proxy written out: either direction, any address incus takes.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "ProxyPort".
 */
export interface ProxyPort {
  bind?: PortBind;
  connect: IntOrString;
  listen: IntOrString;
  /**
   * incus device name. Default: `port-<bind>-<listen port>`.
   */
  name?: string | null;
  /**
   * Extra proxy device properties (`nat`, `proxy_protocol`, ...), verbatim.
   */
  options?: {
    [k: string]: Scalar;
  };
}
/**
 * A service's use of a secret.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "SecretRef".
 */
export interface SecretRef {
  gid?: number | null;
  /**
   * Octal mode, e.g. `0400` (default) or `"0440"`.
   */
  mode?: IntOrString | null;
  /**
   * The top-level secret's key.
   */
  source: string;
  /**
   * File name under `/run/secrets`, or an absolute path. Default: `source`.
   */
  target?: string | null;
  /**
   * Owner in the guest: a uid. Default: the service's numeric `user`, else 0.
   */
  uid?: number | null;
}
/**
 * The long form of a mount.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "VolumeMount".
 */
export interface VolumeMount {
  /**
   * incus device name. Default: derived from the target. Set it to adopt an
   * existing device under a known name.
   */
  device?: string | null;
  external?: BoolOrString;
  /**
   * Extra disk device properties (`shift`, `propagation`, ...), verbatim.
   */
  options?: {
    [k: string]: Scalar;
  };
  /**
   * Named volumes only: chown the mount point to this guest user (`dev`,
   * `dev:dev` or `1000:1000`) after it is attached, plus any root-owned
   * parents inside that user's home that the mount conjured.
   */
  owner?: IntOrString | null;
  /**
   * Named volumes only: the storage pool. Default: the top-level volume's
   * pool, else the sandbox's root pool.
   */
  pool?: string | null;
  read_only?: BoolOrString;
  /**
   * Host path to bind-mount (relative paths resolve against the compose
   * file's directory, `~` expands, symlinks are resolved), or the key of a
   * named volume.
   */
  source: string;
  /**
   * Absolute path inside the guest.
   */
  target: string;
  /**
   * `bind` (a host path) or `volume` (a named volume). Default: `bind` when
   * `source` starts with `/`, `.` or `~`, else `volume`.
   */
  type?: MountType | null;
  volume?: VolumeOptions;
}
/**
 * docker's `volume:` block of a long-form mount.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "VolumeOptions".
 */
export interface VolumeOptions {
  nocopy?: BoolOrString;
}
/**
 * A named custom storage volume.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "NamedVolumeSpec".
 */
export interface NamedVolumeSpec {
  /**
   * Volume config keys (e.g. `size: 10GiB`), applied only at creation.
   */
  config?: {
    [k: string]: Scalar;
  };
  external?: BoolOrString;
  /**
   * The incus volume name. Default: `<project>_<key>`, or the key itself
   * for an `external` volume.
   */
  name?: string | null;
  /**
   * Storage pool. `auto` (default) means the same pool the sandbox uses
   * (`storage`), resolved the same way.
   */
  pool?: string | null;
}
