// Generated by scripts/gen-types.ts from `isb schema`. Do not edit by hand.
// Field names are exactly those of the compose YAML (docs/spec.md).

/**
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "IntOrString".
 */
export type IntOrString = number | string;
/**
 * A scalar (string, number or boolean) read as a string.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "Scalar".
 */
export type Scalar = string | boolean | number;
/**
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "BoolOrString".
 */
export type BoolOrString = boolean | string;
/**
 * idmap handling.
 *
 * The usual need is "host uid/gid 1000 must be the guest's uid/gid 1000 so a
 * bind-mounted checkout is writable". Whether that needs `raw.idmap` depends on
 * the host: when root's subordinate id range (in `/etc/subuid`, `/etc/subgid`)
 * already contains the host id, the default map covers it and asking for
 * `raw.idmap` is refused by incus ("Host ID is in the range of subids"); when
 * it does not (a separate `root:1000:1` delegation only permits the mapping),
 * `raw.idmap` is required.
 *
 * Forms:
 * - `auto`: map 1000:1000 ↔ 1000:1000 only where needed (per id, uid and gid
 *   checked separately).
 * - `none`: never set `raw.idmap`.
 * - `always`: always set it for 1000 ↔ 1000.
 * - `{mode: auto|always, host_uid, host_gid, guest_uid, guest_gid}`: other ids.
 * - `{raw: "both 1000 1000"}`: an explicit `raw.idmap` value.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "IdmapSpec".
 */
export type IdmapSpec = IdmapMode | IdmapMap | IdmapRaw;
/**
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "IdmapMode".
 */
export type IdmapMode = "auto" | "none" | "always";
/**
 * Which side listens.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "PortBind".
 */
export type PortBind = "host" | "guest";
/**
 * A readiness check. "Running" alone is not ready: networking comes up a beat
 * after the instance does.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "ReadyCheck".
 */
export type ReadyCheck =
  | "running"
  | "agent"
  | "default_route"
  | {
      user_exists: string;
    }
  | {
      path_writable: string;
    }
  | {
      command: string[];
    };
/**
 * Instance type.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "InstanceType".
 */
export type InstanceType = "container" | "virtual-machine" | "vm";

/**
 * A compose-style file: named volumes plus any number of sandboxes.
 */
export interface ComposeFile {
  /**
   * Project name. Default sandbox names are `<name>-<service>`. Defaults to
   * the directory holding the first compose file.
   */
  name?: string | null;
  /**
   * incus project to operate in (default: `default`).
   */
  project?: string | null;
  /**
   * Sandboxes, keyed by service name.
   */
  sandboxes?: {
    [k: string]: SandboxSpec;
  };
  /**
   * Named custom storage volumes, created if missing before any sandbox that
   * uses them. Keys are volume names.
   */
  volumes?: {
    [k: string]: NamedVolumeSpec;
  };
}
/**
 * Everything about one sandbox.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "SandboxSpec".
 */
export interface SandboxSpec {
  /**
   * CPU limit (`limits.cpu`): a count like `8` or a set like `0-3`.
   */
  cpus?: IntOrString | null;
  /**
   * Instance environment (`environment.<KEY>`), seen by every exec. Not for
   * secrets: it is plain instance config, readable by anyone who can read the
   * instance.
   */
  env?: {
    [k: string]: Scalar;
  };
  exec?: ExecDefaults;
  /**
   * uid/gid mapping so a host user can write bind mounts. See [`IdmapSpec`].
   */
  idmap?: IdmapSpec | null;
  /**
   * Image: a local alias or fingerprint (`dev-base`), or `remote:alias` for a
   * well-known remote (`images:debian/12`, `ubuntu:24.04`). A local alias that
   * does not exist is an error before anything is created.
   */
  image?: string;
  /**
   * Labels, stored as `user.<key>` config keys. Used by `isb ls --label` and
   * `isb prune`. isb never removes a label it was not told about.
   */
  labels?: {
    [k: string]: Scalar;
  };
  /**
   * Memory limit (`limits.memory`), e.g. `8GiB`.
   */
  memory?: IntOrString | null;
  /**
   * incus instance name: at most 63 characters of `[a-z0-9-]` (case-insensitive),
   * starting with a letter. In a compose file it defaults to `<project>-<service>`.
   */
  name?: string | null;
  /**
   * Proxy devices (port forwards), in either direction.
   */
  ports?: PortSpec[];
  /**
   * Run privileged (`security.privileged`). Omit to leave the incus default
   * (unprivileged); `false` pins it explicitly.
   */
  privileged?: BoolOrString | null;
  /**
   * Profiles to apply, in order. Default: `[default]`. Fixed at creation.
   */
  profiles?: string[] | null;
  /**
   * Extra instance config keys, set verbatim (escape hatch).
   */
  raw_config?: {
    [k: string]: Scalar;
  };
  /**
   * Extra devices, set verbatim (escape hatch). Keys are device names.
   */
  raw_devices?: {
    [k: string]: {
      [k: string]: Scalar;
    };
  };
  /**
   * Readiness checks, run in order after every start/ensure. Default:
   * `[running]` for a container, `[running, agent]` for a VM.
   */
  ready?: ReadyCheck[] | null;
  /**
   * Deadline for all readiness checks together, e.g. `90s`. Default: `60s`
   * for a container, `300s` for a VM.
   */
  ready_timeout?: IntOrString | null;
  /**
   * Storage pool for the root disk. `auto` (default): `incus-zfs` if it exists,
   * else `default`, else the first pool. Fixed at creation.
   */
  storage?: string | null;
  type?: InstanceType;
  /**
   * Mounts, keyed by the absolute path inside the guest.
   */
  volumes?: {
    [k: string]: VolumeSpec;
  };
}
/**
 * Defaults for exec into a sandbox. Per-call options override them.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "ExecDefaults".
 */
export interface ExecDefaults {
  /**
   * Working directory in the guest.
   */
  cwd?: string | null;
  /**
   * Environment for exec (merged over the instance `env`).
   */
  env?: {
    [k: string]: Scalar;
  };
  login?: BoolOrString;
  /**
   * Guest user: a name (`dev`), `uid`, or `uid:gid`. Names are resolved in the
   * guest, and set HOME/USER/LOGNAME unless given in env.
   */
  user?: IntOrString | null;
}
/**
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "IdmapMap".
 */
export interface IdmapMap {
  guest_gid?: number;
  guest_uid?: number;
  host_gid?: number;
  host_uid?: number;
  mode?: IdmapMode;
}
/**
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "IdmapRaw".
 */
export interface IdmapRaw {
  /**
   * Value for `raw.idmap`, verbatim.
   */
  raw: string;
}
/**
 * An incus proxy device.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "PortSpec".
 */
export interface PortSpec {
  bind?: PortBind;
  connect: IntOrString;
  listen: IntOrString;
  /**
   * Device name. Default: `port-<bind>-<listen port>`.
   */
  name?: string | null;
  /**
   * Extra proxy device properties (`nat`, `proxy_protocol`, ...), verbatim.
   */
  options?: {
    [k: string]: Scalar;
  };
  /**
   * Host-bound TCP/UDP only: if the listen port is taken, try the next one, up
   * to this many more. The chosen address is printed and a device already
   * listening anywhere in the range counts as correct.
   */
  search?: IntOrString | null;
}
/**
 * A mount. Exactly one of `bind` or `named`.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "VolumeSpec".
 */
export interface VolumeSpec {
  /**
   * Host path to bind-mount. Relative paths resolve against the compose file's
   * directory; `~` expands; symlinks are resolved.
   */
  bind?: string | null;
  /**
   * Device name. Default: derived from the guest path. Set it to adopt an
   * existing device under a known name.
   */
  device?: string | null;
  external?: BoolOrString;
  /**
   * Named custom storage volume to mount (created if missing unless declared
   * `external`).
   */
  named?: string | null;
  /**
   * Extra disk device properties (`shift`, `propagation`, ...), verbatim.
   */
  options?: {
    [k: string]: Scalar;
  };
  /**
   * Named volumes only: chown the mount point to this guest user (`dev`,
   * `dev:dev` or `1000:1000`) after it is attached, plus any root-owned
   * parents inside that user's home that the mount conjured.
   */
  owner?: IntOrString | null;
  /**
   * Pool of the named volume. Default: the top-level volume's pool, else `auto`.
   */
  pool?: string | null;
  readonly?: BoolOrString;
}
/**
 * A named custom storage volume.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "NamedVolumeSpec".
 */
export interface NamedVolumeSpec {
  /**
   * Volume config keys (e.g. `size: 10GiB`), applied only at creation.
   */
  config?: {
    [k: string]: Scalar;
  };
  external?: BoolOrString;
  /**
   * Storage pool. `auto` (default) means the same pool the sandbox uses
   * (`storage`), resolved the same way.
   */
  pool?: string | null;
}
