// Generated by scripts/gen-types.ts from `isb schema`. Do not edit by hand.
// Field names are exactly those of the compose YAML (docs/spec.md).

/**
 * A command: argv, or a string split the way a shell splits words.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "Command".
 */
export type Command = string | Scalar[];
/**
 * A scalar (string, number or boolean) read as a string.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "Scalar".
 */
export type Scalar = string | boolean | number;
/**
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "IntOrString".
 */
export type IntOrString = number | string;
/**
 * A map, or docker's list of `KEY=VALUE` strings.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "MapOrList".
 */
export type MapOrList =
  | {
      [k: string]: Scalar;
    }
  | string[];
/**
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "BoolOrString".
 */
export type BoolOrString = boolean | string;
/**
 * idmap handling.
 *
 * The usual need is "host uid/gid 1000 must be the guest's uid/gid 1000 so a
 * bind-mounted checkout is writable". Whether that needs `raw.idmap` depends on
 * the host: when root's subordinate id range (in `/etc/subuid`, `/etc/subgid`)
 * already contains the host id, the default map covers it and asking for
 * `raw.idmap` is refused by incus ("Host ID is in the range of subids"); when
 * it does not (a separate `root:1000:1` delegation only permits the mapping),
 * `raw.idmap` is required.
 *
 * Forms:
 * - `auto`: map 1000:1000 ↔ 1000:1000 only where needed (per id, uid and gid
 *   checked separately).
 * - `none`: never set `raw.idmap`.
 * - `always`: always set it for 1000 ↔ 1000.
 * - `{mode: auto|always, host_uid, host_gid, guest_uid, guest_gid}`: other ids.
 * - `{raw: "both 1000 1000"}`: an explicit `raw.idmap` value.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "IdmapSpec".
 */
export type IdmapSpec = IdmapMode | IdmapMap | IdmapRaw;
/**
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "IdmapMode".
 */
export type IdmapMode = "auto" | "none" | "always";
/**
 * A published port, docker style, or an incus proxy in either direction.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "PortSpec".
 */
export type PortSpec = string | PortMapping | ProxyPort;
/**
 * Which side listens.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "PortBind".
 */
export type PortBind = "host" | "guest";
/**
 * A readiness check. "Running" alone is not ready: networking comes up a beat
 * after the instance does.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "ReadyCheck".
 */
export type ReadyCheck =
  | "running"
  | "agent"
  | "default_route"
  | {
      user_exists: string;
    }
  | {
      path_writable: string;
    }
  | {
      command: string[];
    };
/**
 * Instance type.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "InstanceType".
 */
export type InstanceType = "container" | "virtual-machine" | "vm";
/**
 * A mount: `SOURCE:TARGET[:OPTIONS]` or the long form.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "VolumeSpec".
 */
export type VolumeSpec = string | VolumeMount;
/**
 * What a mount's `source` is.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "MountType".
 */
export type MountType = "bind" | "volume";

/**
 * A compose file: named volumes plus any number of services, each one
 * sandbox. Mirrors docker compose wherever incus allows.
 */
export interface ComposeFile {
  /**
   * incus project to operate in (default: `default`).
   */
  incus_project?: string | null;
  /**
   * Project name. Default sandbox names are `<name>-<service>` and named
   * volumes are `<name>_<volume>`. Defaults to the directory holding the
   * first compose file.
   */
  name?: string | null;
  /**
   * Sandboxes, keyed by service name.
   */
  services?: {
    [k: string]: SandboxSpec;
  };
  /**
   * Named custom storage volumes, created if missing before any sandbox that
   * uses them. Keys are what services refer to.
   */
  volumes?: {
    [k: string]: NamedVolumeSpec;
  };
}
/**
 * Everything about one sandbox: a compose service.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "SandboxSpec".
 */
export interface SandboxSpec {
  /**
   * The sandbox's main command, run by a foreground `isb up` once the
   * sandbox is ready, as `user` in `working_dir`. Its output is streamed,
   * and `up` stops the sandbox when every command has exited. A list is
   * argv; a string is split like a shell would split it, without running
   * one. Never part of the instance, so changing it is not drift.
   */
  command?: Command | null;
  /**
   * incus instance name: at most 63 characters of `[a-z0-9-]` (case-insensitive),
   * starting with a letter. In a compose file it defaults to `<project>-<service>`.
   */
  container_name?: string | null;
  /**
   * Number of CPUs (`limits.cpu`), a whole number like `8`.
   */
  cpus?: IntOrString | null;
  /**
   * CPUs to pin to (`limits.cpu`), e.g. `0-3` or `0,2`. Excludes `cpus`.
   */
  cpuset?: IntOrString | null;
  environment?: MapOrList;
  exec?: ExecSpec;
  /**
   * uid/gid mapping so a host user can write bind mounts. See [`IdmapSpec`].
   */
  idmap?: IdmapSpec | null;
  /**
   * Image: a local alias or fingerprint (`dev-base`), or `remote:alias` for a
   * well-known remote (`images:debian/12`, `ubuntu:24.04`). A local alias that
   * does not exist is an error before anything is created.
   */
  image?: string;
  /**
   * incus profiles to apply, in order. Default: `[default]`. Fixed at creation.
   */
  incus_profiles?: string[] | null;
  labels?: MapOrList;
  /**
   * Memory limit (`limits.memory`): docker units (`512m`, `8g`, bytes) or
   * incus ones (`8GiB`, `50%`).
   */
  mem_limit?: IntOrString | null;
  /**
   * Published ports (`[HOST_IP:]PUBLISHED:TARGET[/PROTOCOL]` or the long
   * form), and incus proxies in either direction (`listen`/`connect`).
   */
  ports?: PortSpec[];
  /**
   * Run privileged (`security.privileged`). Omit to leave the incus default
   * (unprivileged); `false` pins it explicitly.
   */
  privileged?: BoolOrString | null;
  /**
   * Extra instance config keys, set verbatim (escape hatch).
   */
  raw_config?: {
    [k: string]: Scalar;
  };
  /**
   * Extra devices, set verbatim (escape hatch). Keys are device names.
   */
  raw_devices?: {
    [k: string]: {
      [k: string]: Scalar;
    };
  };
  /**
   * Readiness checks, run in order after every start/ensure. Default:
   * `[running]` for a container, `[running, agent]` for a VM.
   */
  ready?: ReadyCheck[] | null;
  /**
   * Deadline for all readiness checks together, e.g. `90s`. Default: `60s`
   * for a container, `300s` for a VM.
   */
  ready_timeout?: IntOrString | null;
  /**
   * Storage pool for the root disk. `auto` (default): `incus-zfs` if it exists,
   * else `default`, else the first pool. Fixed at creation.
   */
  storage?: string | null;
  type?: InstanceType;
  /**
   * Guest user for `command`, `isb exec` and `path_writable`: a name
   * (`dev`), `uid`, `uid:gid` or `name:group`. Default root.
   */
  user?: IntOrString | null;
  /**
   * Mounts: `SOURCE:TARGET[:OPTIONS]` or the long form. A source starting
   * with `/`, `.` or `~` is a host path; anything else is a named volume.
   */
  volumes?: VolumeSpec[];
  /**
   * Working directory for `command` and `isb exec`. Default: the user's home.
   */
  working_dir?: string | null;
}
/**
 * The `exec:` block of a service: exec defaults with no docker equivalent.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "ExecSpec".
 */
export interface ExecSpec {
  env?: MapOrList;
  login?: BoolOrString;
}
/**
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "IdmapMap".
 */
export interface IdmapMap {
  guest_gid?: number;
  guest_uid?: number;
  host_gid?: number;
  host_uid?: number;
  mode?: IdmapMode;
}
/**
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "IdmapRaw".
 */
export interface IdmapRaw {
  /**
   * Value for `raw.idmap`, verbatim.
   */
  raw: string;
}
/**
 * Docker's long port syntax.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "PortMapping".
 */
export interface PortMapping {
  /**
   * Host address to listen on. Default `127.0.0.1` (docker's is `0.0.0.0`).
   */
  host_ip?: string | null;
  /**
   * incus device name. Default: `port-host-<published>`.
   */
  name?: string | null;
  /**
   * Extra proxy device properties (`proxy_protocol`, ...), verbatim.
   */
  options?: {
    [k: string]: Scalar;
  };
  /**
   * `tcp` (default) or `udp`.
   */
  protocol?: string | null;
  published: IntOrString;
  target: IntOrString;
}
/**
 * An incus proxy written out: either direction, any address incus takes.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "ProxyPort".
 */
export interface ProxyPort {
  bind?: PortBind;
  connect: IntOrString;
  listen: IntOrString;
  /**
   * incus device name. Default: `port-<bind>-<listen port>`.
   */
  name?: string | null;
  /**
   * Extra proxy device properties (`nat`, `proxy_protocol`, ...), verbatim.
   */
  options?: {
    [k: string]: Scalar;
  };
}
/**
 * The long form of a mount.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "VolumeMount".
 */
export interface VolumeMount {
  /**
   * incus device name. Default: derived from the target. Set it to adopt an
   * existing device under a known name.
   */
  device?: string | null;
  external?: BoolOrString;
  /**
   * Extra disk device properties (`shift`, `propagation`, ...), verbatim.
   */
  options?: {
    [k: string]: Scalar;
  };
  /**
   * Named volumes only: chown the mount point to this guest user (`dev`,
   * `dev:dev` or `1000:1000`) after it is attached, plus any root-owned
   * parents inside that user's home that the mount conjured.
   */
  owner?: IntOrString | null;
  /**
   * Named volumes only: the storage pool. Default: the top-level volume's
   * pool, else the sandbox's root pool.
   */
  pool?: string | null;
  read_only?: BoolOrString;
  /**
   * Host path to bind-mount (relative paths resolve against the compose
   * file's directory, `~` expands, symlinks are resolved), or the key of a
   * named volume.
   */
  source: string;
  /**
   * Absolute path inside the guest.
   */
  target: string;
  /**
   * `bind` (a host path) or `volume` (a named volume). Default: `bind` when
   * `source` starts with `/`, `.` or `~`, else `volume`.
   */
  type?: MountType | null;
}
/**
 * A named custom storage volume.
 *
 * This interface was referenced by `ComposeFile`'s JSON-Schema
 * via the `definition` "NamedVolumeSpec".
 */
export interface NamedVolumeSpec {
  /**
   * Volume config keys (e.g. `size: 10GiB`), applied only at creation.
   */
  config?: {
    [k: string]: Scalar;
  };
  external?: BoolOrString;
  /**
   * The incus volume name. Default: `<project>_<key>`, or the key itself
   * for an `external` volume.
   */
  name?: string | null;
  /**
   * Storage pool. `auto` (default) means the same pool the sandbox uses
   * (`storage`), resolved the same way.
   */
  pool?: string | null;
}
